- README.md
- app/model/schema/token.py
- tests/test_app_routers_bond_tokens_POST.py
- tests/test_app_routers_share_tokens_POST.py
> feat: Add the maximum string length for token's attribute

- app/model/schema/token.py
- tests/test_app_routers_bond_tokens_POST.py
> fix: validate purpose max length

- app/model/schema/ledger.py
- app/model/schema/notification.py
- app/model/schema/token.py
- app/model/schema/transfer.py
- app/model/schema/types.py
- tests/model/blockchain/test_token_IbetStraightBond.py
- tests/test_app_routers_bond_tokens_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_POST.py
- tests/test_app_routers_share_tokens_POST.py
- tests/test_app_routers_share_tokens_{token_address}_POST.py
> feat: date format regex checking

- app/model/schema/ledger.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
> fix: inconsistent validations

- config.py
- tests/test_app_routers_accounts_POST.py
- tests/test_app_routers_accounts_{issuer_address}_eoa_password_POST.py
- tests/test_app_routers_accounts_{issuer_address}_rsa_passphrase_POST.py
- tests/test_app_routers_accounts_{issuer_address}_rsakey_POST.py
> feat: change available password character

- batch/processor_create_utxo.py
- tests/test_batch_processor_create_utxo.py
> feat: Mod true setting timing

- app/routers/bond.py
- app/routers/ledger.py
- app/routers/notification.py
- app/routers/share.py
- tests/test_app_routers_bond_tokens_{token_address}_holders_{account_address}_personal_info_POST.py
- tests/test_app_routers_ledger_{token_address}_details_data_GET.py
- tests/test_app_routers_ledger_{token_address}_details_data_POST.py
- tests/test_app_routers_ledger_{token_address}_details_data_{data_id}_DELETE.py
- tests/test_app_routers_ledger_{token_address}_details_data_{data_id}_GET.py
- tests/test_app_routers_ledger_{token_address}_details_data_{data_id}_POST.py
- tests/test_app_routers_ledger_{token_address}_history_GET.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
- tests/test_app_routers_ledger_{token_address}_template_DELETE.py
- tests/test_app_routers_ledger_{token_address}_template_GET.py
- tests/test_app_routers_ledger_{token_address}_template_POST.py
- tests/test_app_routers_notifications_{notice_id}_DELETE.py
- tests/test_app_routers_share_tokens_{token_address}_holders_{account_address}_personal_info_POST.py
> feat: Mod status code for NotFound

- app/model/blockchain/exchange.py
- app/model/blockchain/token.py
- app/utils/contract_utils.py
- batch/indexer_personal_info.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_transfer_approval.py
- batch/processor_create_utxo.py
- tests/model/blockchain/test_exchange_IbetExchangeInterface.py
- tests/model/blockchain/test_token_IbetShare.py
- tests/model/blockchain/test_token_IbetStraightBond.py
> feat: backward compatible function call

- batch/indexer_position_bond.py
> fix: set pending_transfer

- batch/indexer_position_bond.py
- batch/indexer_position_share.py
> fix: approval function events

- README.md
- config.py
> feat: add explanation of API documentation

- batch/indexer_transfer_approval.py
> fix: automatic approval notification

- README.md
- docker-compose.yml
> feat: upgrade PostgreSQL

- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/processor_create_utxo.py
> fix: Error in indexer when ordering make on ibetExchange

- app/model/db/ledger_template.py
- app/model/db/scheduled_events.py
- app/model/schema/ledger.py
- app/model/schema/scheduled_events.py
- app/model/schema/types.py
- app/routers/bond.py
- app/routers/ledger.py
- app/routers/share.py
- app/utils/ledger_utils.py
- batch/processor_scheduled_events.py
- tests/test_app_routers_bond_tokens_{token_address}_scheduled_events_GET.py
- tests/test_app_routers_bond_tokens_{token_address}_scheduled_events_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_scheduled_events_{scheduled_event_id}_DELETE.py
- tests/test_app_routers_bond_tokens_{token_address}_scheduled_events_{scheduled_event_id}_GET.py
- tests/test_app_routers_bond_transfers_{token_Address}_GET.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
- tests/test_app_routers_ledger_{token_address}_template_DELETE.py
- tests/test_app_routers_ledger_{token_address}_template_GET.py
- tests/test_app_routers_ledger_{token_address}_template_POST.py
- tests/test_app_routers_share_tokens_{token_address}_scheduled_events_GET.py
- tests/test_app_routers_share_tokens_{token_address}_scheduled_events_POST.py
- tests/test_app_routers_share_tokens_{token_address}_scheduled_events_{scheduled_event_id}_DELETE.py
- tests/test_app_routers_share_tokens_{token_address}_scheduled_events_{scheduled_event_id}_GET.py
- tests/test_app_routers_share_transfers_{token_Address}_GET.py
- tests/test_batch_processor_scheduled_events.py
- tests/test_utils_ledger_utils.py
> feat: enum request

- app/model/schema/__init__.py
- app/model/schema/transfer.py
- app/model/schema/types.py
- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_transfer_approvals_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_{id}_GET.py
- tests/test_app_routers_share_transfer_approvals_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_{id}_GET.py
> feat: sotrable and fillterable to the transfer approval API

- app/routers/bond.py
- app/routers/ledger.py
- app/routers/share.py
- tests/test_app_routers_bond_transfer_approvals_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_bond_transfers_{token_Address}_GET.py
- tests/test_app_routers_share_transfer_approvals_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_share_transfers_{token_Address}_GET.py
> feat: mod result_set.count

- app/model/blockchain/token.py
- app/routers/bond.py
- app/routers/share.py
- app/utils/contract_utils.py
- batch/processor_create_utxo.py
- batch/processor_update_token.py
- tests/model/blockchain/test_token_IbetShare.py
- tests/model/blockchain/test_token_IbetStraightBond.py
- tests/test_app_routers_bond_tokens_POST.py
- tests/test_app_routers_share_tokens_POST.py
- tests/test_batch_processor_create_utxo.py
- tests/test_batch_processor_update_token.py
- tests/test_utils_contract_utils.py
> feat: add issuer to legher

- app/model/blockchain/token.py
- tests/model/blockchain/test_exchange_IbetSecurityTokenEscrow.py
- tests/model/blockchain/test_token_IbetShare.py
- tests/model/blockchain/test_token_IbetStraightBond.py
> fix: return cancel_transfer

- app/model/blockchain/personal_info.py
- app/utils/contract_utils.py
- batch/indexer_e2e_messaging.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- batch/processor_create_utxo.py
Implemented getLogs for backward or forward compatibility.
> feat: Backward or forward compatible getLogs

- batch/indexer_transfer.py
> fix: indexer_transfer's module load

- batch/processor_create_utxo.py
- tests/test_batch_processor_create_utxo.py
> fix: Spend UTXO when Redeem

- app/model/db/notification.py
- app/model/schema/notification.py
- batch/indexer_transfer_approval.py
- tests/test_batch_indexer_transfer_approval.py
> feat: Add notification upon approval of token transfer

- requirements.lock
- requirements.txt
> feat: upgrade fastapi

- requirements.lock
- requirements.txt
> feat: upgrade gunicorn + uvicorn

- app/utils/contract_utils.py
> fix: ABIEventFunctionNotFound

- app/routers/file.py
- tests/test_app_routers_files_POST.py
> feat: add response for POST

- app/utils/contract_utils.py
> fix: ABIFunctionNotFound

- app/routers/ledger.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
> fix: performance improvement

- Dockerfile
- tests/Dockerfile
> feat: update python

- batch/indexer_personal_info.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_token_holders.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- tests/test_batch_indexer_personal_info.py
- tests/test_batch_indexer_position_bond.py
- tests/test_batch_indexer_position_share.py
- tests/test_batch_indexer_token_holders.py
- tests/test_batch_indexer_transfer.py
- tests/test_batch_indexer_transfer_approval.py
- tests/utils/contract_utils.py
> feat: add INDEXER batch’s unit test

- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_GET.py
> feat: Add status array from TransferApplovalsAPI

- app/model/db/idx_personal_info.py
- app/model/schema/personal_info.py
- tests/test_app_routers_bond_tokens_{token_address}_holders_{account_address}_personal_info_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_personal_info_POST.py
- tests/test_app_routers_share_tokens_{token_address}_holders_{account_address}_personal_info_POST.py
- tests/test_app_routers_share_tokens_{token_address}_personal_info_POST.py
> feat: Change personal information items to Optional

- docker-compose.yml
> feat: upgrade postgres

- app/routers/e2e_messaging.py
- tests/test_app_routers_e2e_messaging_messages_GET.py
> feat: Change default sort order

- app/database.py
- config.py
> feat: delete unused config

- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_tokens_{token_address}_holders_GET.py
- tests/test_app_routers_share_tokens_{token_address}_holders_GET.py
- tests/test_batch_indexer_token_holders.py
> feat: Excluding former holders in holders endpoint 

- app/routers/account.py
- app/routers/bond.py
- app/routers/e2e_messaging.py
- app/routers/file.py
- app/routers/position.py
- app/routers/share.py
- app/routers/token_holders.py
close #357 
- Added deprecated warning log output.
- Removed unnecessary imports.
> feat: deprecation warning

- app/model/schema/token.py
- tests/model/blockchain/test_token_IbetShare.py
- tests/model/blockchain/test_token_IbetStraightBond.py
- tests/test_app_routers_bond_bulk_transfer_POST.py
- tests/test_app_routers_bond_tokens_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_additional_issue_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_additional_issue_batch_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_redeem_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_redeem_batch_POST.py
- tests/test_app_routers_bond_transfers_POST.py
- tests/test_app_routers_share_bulk_transfer_POST.py
- tests/test_app_routers_share_tokens_POST.py
- tests/test_app_routers_share_tokens_{token_address}_additional_issue_POST.py
- tests/test_app_routers_share_tokens_{token_address}_additional_issue_batch_POST.py
- tests/test_app_routers_share_tokens_{token_address}_redeem_POST.py
- tests/test_app_routers_share_tokens_{token_address}_redeem_batch_POST.py
- tests/test_app_routers_share_transfers_POST.py
> feat: increase the maximum supply

- app/model/schema/__init__.py
- app/model/schema/holder.py
- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_tokens_{token_address}_holders_count_GET.py
- tests/test_app_routers_share_tokens_{token_address}_holders_count_GET.py
close #360 
- GET: /bond/tokens/{token_address}/holders/count
- GET: /share/tokens/{token_address}/holders/count
> feat: add API to get the number of holders

- app/routers/share.py
- tests/test_app_routers_share_tokens_{token_address}_additional_issue_POST.py
- tests/test_app_routers_share_tokens_{token_address}_additional_issue_batch_POST.py
- tests/test_app_routers_share_tokens_{token_address}_redeem_POST.py
- tests/test_app_routers_share_tokens_{token_address}_redeem_batch_POST.py
- tests/test_app_routers_share_transfer_approvals_GET.py
A bug existed in the #351 PR and I have fixed it.
> fix: token type bug

- README.md
- README_JA.md
> Add readme ja

- app/model/db/upload_file.py
- app/model/schema/file.py
- app/routers/file.py
- migrations/versions/b1844596cae5_v22_9_0_feature_383.py
- tests/test_app_routers_files_GET.py
- tests/test_app_routers_files_POST.py
> feat: Change null to an empty string

- app/log.py
- app/main.py
Close: #393 
**Output log example**
> feat: response time log

- app/model/blockchain/token.py
> fix: Correct floating-point arithmetic errors

- docker-compose.yml
Supported postgresql version upgrades
> feat: support postgresql 13.8

- app/utils/contract_utils.py
> feat: Add exception handling for backward compatible function call

- batch/processor_monitor_block_sync.py
- config.py
- tests/test_batch_processor_monitor_block_sync.py
> feat: Variable block synchronization delay threshold

- batch/processor_create_utxo.py
- config.py
- tests/test_batch_processor_create_utxo.py
> feat: Change ledger creation interval to exactly 10 minutes

- app/model/blockchain/e2e_messaging.py
- app/model/blockchain/exchange.py
- app/model/blockchain/personal_info.py
- app/model/blockchain/token.py
- app/model/blockchain/token_list.py
- app/utils/contract_utils.py
- requirements.lock
- requirements.txt
- tests/conftest.py
- tests/model/blockchain/test_PersonalInfo.py
- tests/model/blockchain/test_exchange_IbetExchangeInterface.py
- tests/model/blockchain/test_exchange_IbetSecurityTokenEscrow.py
- tests/test_batch_indexer_issue_redeem.py
- tests/test_batch_indexer_personal_info.py
- tests/test_batch_indexer_position_bond.py
- tests/test_batch_indexer_position_share.py
- tests/test_batch_indexer_transfer.py
- tests/test_batch_indexer_transfer_approval.py
- tests/test_batch_processor_create_utxo.py
- tests/test_batch_processor_modify_personal_info.py
- tests/test_batch_processor_monitor_block_sync.py
- tests/test_utils_contract_utils.py
- tests/test_utils_ledger_utils.py
- tests/utils/contract_utils.py
I upgraded web3py to the latest version.
> feat: upgrade web3py

- requirements.lock
> feat: update sqlalchemy

- config.py
- tests/test_batch_processor_monitor_block_sync.py
> feat: change the default value of `BLOCK_SYNC_REMAINING_THRESHOLD`

- requirements.lock
- requirements.txt
Upgraded uvicorn.
- https://github.com/encode/uvicorn/releases/tag/0.19.0
- https://github.com/encode/uvicorn/releases/tag/0.20.0
> feat: Upgrade uvicorn

- app/routers/file.py
> feat: Use only necessary columns of file

- app/model/schema/token.py
- tests/test_app_routers_bond_tokens_{token_address}_POST.py
- tests/test_app_routers_share_tokens_{token_address}_POST.py
- Expanded token memo field length from 2000 to 10000.
> feat: expand token memo field length

- bin/run_server.sh
Close #440 
- Add keep-alive option
> feat: keep-alive option

- batch/indexer_block_tx_data.py
- batch/indexer_e2e_messaging.py
- batch/indexer_issue_redeem.py
- batch/indexer_personal_info.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_token_holders.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- batch/processor_batch_issue_redeem.py
- batch/processor_batch_register_personal_info.py
- batch/processor_bulk_transfer.py
- batch/processor_create_utxo.py
- batch/processor_generate_rsa_key.py
- batch/processor_modify_personal_info.py
- batch/processor_monitor_block_sync.py
- batch/processor_rotate_e2e_messaging_rsa_key.py
- batch/processor_scheduled_events.py
- batch/processor_update_token.py
- tests/test_batch_indexer_issue_redeem.py
- tests/test_batch_indexer_personal_info.py
- tests/test_batch_indexer_position_bond.py
- tests/test_batch_indexer_position_share.py
- tests/test_batch_indexer_token_holders.py
- tests/test_batch_indexer_transfer.py
I have made the following two improvements to the batch log
- Improved log output information.
- Improved log output timing.
> Improve batch log output

- batch/indexer_e2e_messaging.py
- batch/indexer_issue_redeem.py
- batch/indexer_personal_info.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- config.py
> fix: Suppress ReadTimeout during node access that occurs in indexer

- batch/indexer_token_holders.py
- batch/indexer_transfer.py
- tests/test_batch_indexer_token_holders.py
- tests/test_batch_indexer_transfer.py
#448 
Fixed two existing batch processes.
- indexer_transfer
- indexer_token_holders
> feat: Added transfer indexing and holders collection creation process to watch for unlock events

- app/model/schema/__init__.py
- app/model/schema/position.py
- app/routers/position.py
- tests/test_app_routers_positions_{account_address}_lock_GET.py
#448
- [NEW] GET: /positions/{account_address}/lock
> feat: Added locked positions API

- app/model/blockchain/token.py
- app/model/blockchain/tx_params/ibet_security_token.py
- app/model/blockchain/tx_params/ibet_share.py
- app/model/blockchain/tx_params/ibet_straight_bond.py
- app/model/schema/__init__.py
- app/model/schema/position.py
- app/routers/position.py
- tests/model/blockchain/test_token_IbetShare.py
- tests/model/blockchain/test_token_IbetStraightBond.py
- tests/test_app_routers_positions_{account_address}_forceunlock_POST.py
close #448 
- [NEW] POST: /positions/{account_address}/force_unlock
> feat: Add force unlock API

- batch/processor_monitor_block_sync.py
- tests/test_batch_processor_monitor_block_sync.py
> feat: Delete remaining past WEB3_HTTP_PROVIDER data

- app/utils/contract_utils.py
Close #379 
- Modified `contract_utils.py` so as to reuse web3 contract factory
- factory is generated when we call `web3.eth.contract` without contract_address arg.
- https://github.com/ethereum/web3.py/blob/v5.31.3/web3/eth.py#L950-L960
- This would slightly reduce memory consumption in indexer batch.
> feat: reuse contract factory

- app/utils/web3_utils.py
> feat: add HTTPError handling to web3_utils

- batch/indexer_token_holders.py
- tests/test_batch_indexer_token_holders.py
> fix: requests.exceptions.ReadTimeout occurs in indexer of Token Holders

- Dockerfile
- tests/Dockerfile
> feat: cleanup unused setuptools

- batch/processor_create_utxo.py
- tests/test_batch_processor_create_utxo.py
Close: #493 
Integration test had been done locally.
> feat: Create UTXO ledger when transfer is occurred from unlock event

- app/model/db/idx_transfer_approval.py
- app/model/schema/transfer.py
- app/routers/bond.py
- app/routers/share.py
- batch/indexer_transfer_approval.py
- tests/test_app_routers_bond_transfer_approvals_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_{id}_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_Address}_{id}_POST.py
- tests/test_app_routers_share_transfer_approvals_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_{id}_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_Address}_{id}_POST.py
- tests/test_batch_indexer_transfer_approval.py
> Add cancellation blocktimestamp

- app/database.py
- app/routers/account.py
- app/routers/bc_explorer.py
- app/routers/bond.py
- app/routers/common.py
- app/routers/e2e_messaging.py
- app/routers/file.py
- app/routers/ledger.py
- app/routers/notification.py
- app/routers/position.py
- app/routers/share.py
- app/routers/token_holders.py
- poetry.lock
- pyproject.toml
> Dependencies using Annotated

- Makefile
- poetry.lock
- pyproject.toml
- Upgraded SQLAlchemy.
- This is mainly focused on https://github.com/sqlalchemy/sqlalchemy/issues/9511 fix.
> feat: upgrade SQLAlchemy

- app/model/blockchain/token.py
- app/routers/bc_explorer.py
- app/routers/bond.py
- app/routers/share.py
- app/routers/token_holders.py
- batch/indexer_issue_redeem.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_token_holders.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- batch/processor_batch_issue_redeem.py
- batch/processor_bulk_transfer.py
- batch/processor_rotate_e2e_messaging_rsa_key.py
- batch/processor_update_token.py
- migrations/versions/a1e5a5a6745e_v23_6_0_feature_497.py
- tests/test_batch_processor_batch_issue_redeem.py
There seems to be a bug in the session type annotation in PyCharm, and it has been fixed to the correct implementation.
https://github.com/sqlalchemy/sqlalchemy/discussions/8741
Please note that this fix will result in a warning until the bug is fixed in PyCharm.
> Session type annotations incorrect in PyCharm

- app/main.py
- app/routers/ledger.py
- app/utils/fastapi.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
> feat: add error response for `Int exceeds 64bit range` exception

- app/model/schema/position.py
- app/routers/position.py
- tests/test_app_routers_positions_{account_address}_forceunlock_POST.py
> feat: Use path parameter account_address in force_unlock API

- poetry.lock
- pyproject.toml
- tests/test_app_routers_files_GET.py
- tests/test_app_routers_token_holders_{token_address}_GET.py
> Bump web3 version

- .github/workflows/codeql-analysis.yml
- .github/workflows/pr.yml
- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- Change psycopg installation option to psycopg-c
- Updated 3rd-party libraries.
> Change to psycopg-c

- batch/indexer_block_tx_data.py
- poetry.lock
- pyproject.toml
> Bump web3py

- app/model/schema/token.py
- tests/test_app_routers_bond_tokens_{token_address}_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_scheduled_events_POST.py
- tests/test_app_routers_share_tokens_{token_address}_POST.py
- tests/test_app_routers_share_tokens_{token_address}_scheduled_events_POST.py
> Add `is_canceled`/`is_redeemed` validation to token update request body

- README.md
- README_JA.md
- docker-compose.yml
> Support PostgreSQL 15

- app/model/schema/transfer.py
- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_transfer_approvals_{token_address}_GET.py
- tests/test_app_routers_bond_transfers_{token_address}_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_address}_GET.py
- tests/test_app_routers_share_transfers_{token_address}_GET.py
> Add `personal_information` to token transfer list API response

- app/model/blockchain/tx_params/ibet_straight_bond.py
- app/model/schema/token.py
- tests/test_app_routers_bond_tokens_POST.py
- tests/test_app_routers_bond_tokens_{token_address}_POST.py
> Fix floating-point arithmetic in validation

- cmd/explorer/pyproject.toml
- cmd/explorer/src/gui/explorer.css
- cmd/explorer/src/gui/screen/block.py
- cmd/explorer/src/gui/screen/transaction.py
- cmd/explorer/src/gui/widget/block_list_table.py
- cmd/explorer/src/gui/widget/menu.py
- cmd/explorer/src/gui/widget/query_panel.py
- cmd/explorer/src/gui/widget/tx_list_table.py
- poetry.lock
- pyproject.toml
Close: #569 
- I have tested bc-explorer with ibet-prime API node on local.
> Bump textual

- Dockerfile
- tests/Dockerfile
Upgraded `setuptools` and `libc-bin` version used in container
> Bump dependencies in container

- app/routers/bond.py
- app/routers/share.py
- cmd/explorer/src/connector/__init__.py
- tests/test_app_routers_bond_transfer_approvals_{token_address}_{id}_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_address}_{id}_GET.py
> Add condition to if statement so as to ensure `transfer_approval_history` has value on personal_info column

- app/model/schema/ledger.py
- cmd/explorer/src/connector/__init__.py
- tests/test_app_routers_ledger_{token_address}_details_data_POST.py
- tests/test_app_routers_ledger_{token_address}_details_data_{data_id}_POST.py
> Fix upper limit check when uploading external data (v23.12)

- app/model/schema/ledger.py
- cmd/explorer/src/connector/__init__.py
- tests/test_app_routers_ledger_{token_address}_details_data_POST.py
- tests/test_app_routers_ledger_{token_address}_details_data_{data_id}_POST.py
Related to #578 
(cherry picked from commit 3ab3df568fd276542c1a84ed5395174c07c812bf)
> Fix upper limit check when uploading external data (v24.3)

- app/model/schema/__init__.py
- app/model/schema/holder.py
- app/model/schema/personal_info.py
- app/model/schema/token.py
- app/model/schema/transfer.py
- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_tokens_{token_address}_additional_issue_GET.py
- tests/test_app_routers_bond_tokens_{token_address}_holders_GET.py
- tests/test_app_routers_bond_tokens_{token_address}_redeem_GET.py
- tests/test_app_routers_bond_transfer_approvals_{token_address}_GET.py
- tests/test_app_routers_bond_transfers_{token_address}_GET.py
- tests/test_app_routers_share_tokens_{token_address}_additional_issue_GET.py
- tests/test_app_routers_share_tokens_{token_address}_holders_GET.py
- tests/test_app_routers_share_tokens_{token_address}_redeem_GET.py
- tests/test_app_routers_share_transfer_approvals_{token_address}_GET.py
- tests/test_app_routers_share_transfers_{token_address}_GET.py
> Add result_set for pagination to token holders API

- Dockerfile
- tests/Dockerfile
> Upgrade Ubuntu

- .pre-commit-config.yaml
- cmd/explorer/src/connector/__init__.py
- poetry.lock
- pyproject.toml
- tests/test_app_routers_bond_tokens_{token_address}_scheduled_events_POST.py
- tests/test_app_routers_share_tokens_{token_address}_scheduled_events_POST.py
Apply patches for the following issues.
- https://github.com/BoostryJP/ibet-Prime/security/dependabot/9
- https://github.com/BoostryJP/ibet-Prime/security/dependabot/10
- https://github.com/BoostryJP/ibet-Prime/security/dependabot/11
- https://github.com/BoostryJP/ibet-Prime/security/dependabot/12
> Bump packages

- app/model/db/token.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- migrations/versions/6814beab6ff6_v24_3_0_feature_582.py
- migrations/versions/cb24da38646e_v24_3_0_feature_592.py
- tests/test_batch_indexer_position_bond.py
- tests/test_batch_indexer_position_share.py
> Issuer position synchronization is limited to initial issuance only

- server.py
> Use asyncio eventloop on API server

- Dockerfile
- tests/Dockerfile
- Add a line to Dockerfile in order to upgrade ubuntu packages in Docker container
> Upgrade ubuntu package in Docker container

- app/main.py
- app/model/blockchain/exchange.py
- app/model/blockchain/tx_params/ibet_security_token_dvp.py
- app/model/db/__init__.py
- app/model/db/dvp_agent_account.py
- app/model/schema/__init__.py
- app/model/schema/settlement.py
- app/routers/settlement.py
- migrations/versions/5954db6ba5f4_v24_6_0_feature_606_2.py
- tests/test_app_routers_settlement_dvp_agent_account_{account_address}_DELETE.py
- tests/test_app_routers_settlement_dvp_agent_account_{account_address}_eoa_password_POST.py
- tests/test_app_routers_settlement_dvp_agent_accounts_GET.py
- tests/test_app_routers_settlement_dvp_agent_accounts_POST.py
- tests/test_app_routers_settlement_dvp_{exchange_address}_deliveries_GET.py
- tests/test_app_routers_settlement_dvp_{exchange_address}_deliveries_POST.py
- tests/test_app_routers_settlement_dvp_{exchange_address}_delivery_{delivery_id}_GET.py
- tests/test_app_routers_settlement_dvp_{exchange_address}_delivery_{delivery_id}_POST.py
- tests/utils/contract_utils.py
Part of: #606 
- Added API endpoints for operation around DVP delivery
- Specifications: https://github.com/BoostryJP/ibet-Prime/issues/606#issuecomment-2047902475
> Add API endpoints for DVP delivery operation

- batch/processor_update_token.py
- cmd/explorer/src/connector/__init__.py
- tests/test_app_routers_settlement_dvp_{exchange_address}_deliveries_POST.py
- tests/test_app_routers_settlement_dvp_{exchange_address}_delivery_{delivery_id}_GET.py
- tests/test_batch_processor_update_token.py
> Fixed to update token attributes of `require_personal_info_registered`

- hardhat.config.js
- package-lock.json
- package.json
- Update the version of hardhat.
- Change hardfork setting back to "berlin".
> Bump hardhat

- app/routers/ledger.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
Fix #615 
There was a mistake in implementing backward compatibility when latest_flg == 1, so I fixed it.
> Fix backward compatibility for some_personal_info_not_registered

- app/routers/ledger.py
- tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
> Fix the logic of __get_personal_info used in ledger history API

- poetry.lock
- pyproject.toml
Add a memory profiler for performance analysis.
https://bloomberg.github.io/memray/
> Add memray

- app/model/schema/token.py
- app/routers/bond.py
- app/routers/share.py
- docs/ibet_prime.yaml
- tests/test_app_routers_bond_tokens_{token_address}_holders_GET.py
- tests/test_app_routers_share_tokens_{token_address}_holders_GET.py
> Add query filter about amount+pending_transfer to ibet token holder API

- app/model/db/idx_personal_info.py
- app/model/schema/personal_info.py
- app/model/schema/token_holders.py
- app/routers/token_holders.py
- batch/indexer_personal_info.py
- docs/ibet_prime.yaml
- migrations/versions/4704529e8fe0_v24_6_0_feature_637.py
- tests/test_app_routers_token_holders_personal_info_history_GET.py
> Store the block_timestamp of personal information as history data

- app/routers/bond.py
- app/routers/share.py
- tests/test_app_routers_bond_transfers_{token_address}_GET.py
- tests/test_app_routers_share_transfers_{token_address}_GET.py
> Make it enable to search/sort with multibyte name on transfers list API

- app/routers/bond.py
- app/routers/share.py
- tests/app/test_bond_tokens_{token_address}_holders_GET.py
- tests/app/test_share_tokens_{token_address}_holders_GET.py
> Use COALESCE function on summed column to replace NULL with 0

- app/routers/share.py
- tests/app/test_healthcheck_GET.py
- Removed unnecessary debug print
> Remove unnecessary debug print

- app/log.py
- Suppressed error logs raised by web3 request manager.
> Suppress error logs raised by web3 module

- Dockerfile
- tests/Dockerfile_unittest
- Fix the number of poetry max workers to 1
- https://python-poetry.org/docs/configuration/#installermax-workers
> Fix the number of poetry max workers

- .dockerignore
- .github/actions/setup-test-image/action.yml
- .github/workflows/pr.yml
- Dockerfile
- tests/Dockerfile_unittest
- tests/qa.sh
- Multi-stage builds and slimmed down image sizes
> Multi-stage builds and slimmed down image sizes

- app/model/blockchain/exchange.py
- app/model/db/notification.py
- app/model/schema/notification.py
- app/model/schema/settlement.py
- app/routers/settlement.py
- batch/indexer_delivery.py
- docs/ibet_prime.yaml
- tests/app/test_notifications_GET.py
- tests/app/test_settlement_dvp_{exchange_address}_deliveries_POST.py
- tests/batch/test_indexer_delivery.py
- Close: #656 
- And modified to return delivery_id when CreateDelivery API is called.
> Add notification type of DvP confirmed/finished

- app/model/schema/__init__.py
- app/routers/settlement.py
- docs/ibet_prime.yaml
> Update API doc of create DvP Delivery

- app/model/schema/token_holders.py
- app/routers/token_holders.py
- docs/ibet_prime.yaml
- tests/app/test_token_holders_{token_address}_collection_{collection_id}_GET.py
> Add pagination for holders collection

- app/model/schema/__init__.py
- app/model/schema/token_holders.py
- app/routers/token_holders.py
- docs/ibet_prime.yaml
- tests/app/test_token_holders_{token_address}_collection_{collection_id}_GET.py
- tests/batch/test_processor_generate_rsa_key.py
> Add sort/filter to holders collection API

- package-lock.json
- https://github.com/BoostryJP/ibet-Prime/security/dependabot/24
> Bump npm packages

- .github/workflows/pr.yml
- .gitignore
- docker-compose.yml
- poetry.lock
- pyproject.toml
- tests/Dockerfile_unittest
- tests/qa.sh
> Measure test coverage

- batch/processor_modify_personal_info.py
- cmd/explorer/src/connector/__init__.py
- tests/batch/test_processor_modify_personal_info.py
> Remove "Failed to decrypt" error log from processor_modify_personal_info.py

- batch/indexer_dvp_delivery.py
- tests/batch/test_indexer_dvp_delivery.py
- Fixed to index dvp delivery events of which the agent_address is related to DVPAgentAccount
> Index dvp_delivery events of which the agent_address is related to DVPAgentAccount

- app/model/schema/__init__.py
- app/model/schema/scheduled_events.py
- app/routers/issuer/bond.py
- app/routers/issuer/share.py
- cmd/explorer/src/connector/__init__.py
- docs/ibet_prime.yaml
- tests/app/test_bond_tokens_{token_address}_scheduled_events_batch_POST.py
- tests/app/test_share_tokens_{token_address}_scheduled_events_batch_POST.py
> Add an API for batch scheduling

- batch/processor_monitor_block_sync.py
- config.py
> Change `EXPECTED_BLOCKS_PER_SEC` from a constant to an environment variable

- cmd/settlement/src/main.py
> Fix to render delivery data list on settlement-cli

- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- tests/batch/test_indexer_position_bond.py
- tests/batch/test_indexer_position_share.py
> Fix long query due to indexer position batches updating the same position record

- app/main.py
- app/routers/misc/sealed_tx.py
- config.py
- docs/ibet_prime.yaml
Related to #689 
- Added a launch mode to run the Sealed-Tx feature independently; `DEDICATED_SEALED_TX_MODE`
- Additionally, made minor fixes.
> Add "dedicated" sealed tx launch mode

- .dockerignore
- .github/workflows/pr.yml
- .gitignore
- pyproject.toml
- tests/qa.sh
- Parallelize pytest execution jobs
> Parallelize pytest execution jobs

- README.md
- README_JA.md
- docker-compose.yml
- package-lock.json
- package.json
- tests/Dockerfile_hardhat
- Support PostgreSQL v16.
- Update the hardhat image.
> Update postgres and hardhat images

- .github/workflows/build.yml
- .github/workflows/pr.yml
Update workflow images
- `chartboost/ruff-action` is no longer maintained.
- `MishaKav/pytest-coverage-comment` started versioning.
> Update github workflows

- app/model/db/__init__.py
- app/model/db/account.py
- app/model/schema/__init__.py
- app/model/schema/account.py
- app/routers/issuer/account.py
- batch/processor_batch_create_child_account.py
- bin/healthcheck_processor.sh
- bin/run_processor.sh
- docs/ibet_prime.yaml
- migrations/versions/18a410bd19b8_v24_12_0_feature_714.py
- tests/app/test_accounts_CreateChildAccountInBatch.py
- tests/batch/test_processor_batch_create_child_account.py
> Add batch creation function for child accounts

- app/model/schema/base/__init__.py
- app/model/schema/base/base.py
- app/model/schema/token_holders.py
- app/routers/issuer/token_holders.py
- docs/ibet_prime.yaml
- tests/app/test_token_holders_ListTokenHoldersPersonalInfo.py
- tests/app/test_token_holders_ListTokenHoldersPersonalInfoHistory.py
- Made the holders' personal info data searchable based on the type of key manager.
> Add key_manager_type query for holders personal info

- app/model/db/ledger.py
- app/utils/ledger_utils.py
- migrations/versions/5a4efe21222c_v24_12_0_feature_708_2.py
- tests/app/utils/test_ledger_utils.py
> fix: Correct duplicate ledger generation

- batch/processor_create_utxo.py
- tests/app/utils/test_ledger_utils.py
- tests/batch/test_processor_create_utxo.py
- Added error handling in `processor_create_utxo.py` for values exceeding DB limits
- Ensures UTXO changes are saved while discarding invalid ledger creation requests when invalid data comes.
> Add error handling in create_utxo batch for values exceeding DB limits

- pyproject.toml
- uv.lock
> Add py-spy and bump pydantic

- app/model/schema/__init__.py
- app/model/schema/personal_info.py
- app/routers/issuer/bond.py
- app/routers/issuer/share.py
- docs/ibet_prime.yaml
- tests/app/test_bond_personal_info_RegisterBondTokenHolderPersonalInfo.py
- tests/app/test_share_personal_info_RegisterShareTokenHolderPersonalInfo.py
- uv.lock
> Add off-chain update option

- app/model/db/__init__.py
- app/model/db/token_holder_extra_info.py
- app/model/db/token_holders_collection.py
- app/model/schema/__init__.py
- app/model/schema/holder.py
- app/model/schema/sealed_tx.py
- app/routers/issuer/bond.py
- app/routers/issuer/share.py
- app/routers/misc/sealed_tx.py
- docs/ibet_prime.yaml
- migrations/versions/3b7e17706e3e_v24_12_0_feature_723.py
- tests/app/test_bond_holders_ListAllBondTokenHolders.py
- tests/app/test_bond_holders_RegisterBondTokenHolderExtraInfo.py
- tests/app/test_bond_holders_RetrieveBondTokenHolder.py
- tests/app/test_sealed_tx_SealedTxRegisterHolderExtraInfo.py
- tests/app/test_sealed_tx_SealedTxRegisterPersonalInfo.py
- tests/app/test_share_holders_ListAllShareTokenHolders.py
- tests/app/test_share_holders_RegisterShareTokenHolderExtraInfo.py
- tests/app/test_share_holders_RetrieveShareTokenHolder.py
> Managing investor's extra information

- batch/indexer_dvp_delivery.py
- batch/processor_batch_register_personal_info.py
- tests/batch/test_processor_register_personal_info.py
> Fix failure notification code generated by `processor_batch_register_personal_info`

- app/exceptions.py
- app/main.py
- docs/ibet_prime.yaml
- tests/app/test_bond_additional_issue_IssueAdditionalBond.py
- tests/app/test_bond_personal_info_RegisterBondTokenHolderPersonalInfo.py
- tests/app/test_bond_redeem_RedeemBond.py
- tests/app/test_bond_tokens_IssueBondToken.py
- tests/app/test_bond_tokens_UpdateBondToken.py
- tests/app/test_bond_transfer_approvals_UpdateBondTokenTransferApprovalStatus.py
- tests/app/test_bond_transfers_TransferBondTokenOwnership.py
- tests/app/test_e2e_messaging_CreateE2EMessagingAccount.py
- tests/app/test_freezelog_RecordNewFreezeLog.py
- tests/app/test_freezelog_UpdateFreezeLog.py
- tests/app/test_positions_ForceUnlock.py
- tests/app/test_settlement_agent_UpdateDVPAgentDelivery.py
- tests/app/test_settlement_issuer_CreateDVPDelivery.py
- tests/app/test_share_additional_issue_IssueAdditionalShare.py
- tests/app/test_share_personal_info_RegisterShareTokenHolderPersonalInfo.py
- tests/app/test_share_redeem_RedeemShare.py
- tests/app/test_share_tokens_IssueShareToken.py
- tests/app/test_share_tokens_UpdateShareToken.py
- tests/app/test_share_transfer_approvals_UpdateShareTokenTransferApprovalStatus.py
- tests/app/test_share_transfers_TransferShareTokenOwnership.py
> Change SendTransactionError status code

- app/utils/contract_utils.py
- batch/indexer_issue_redeem.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- batch/processor_create_utxo.py
- Related to #379 
- Reduced memory usage of batch containers by extracting events attribute from async contract class.
> Extract events from async contract instance to reduce memory usage

- app/model/db/__init__.py
- app/model/db/token.py
- app/model/schema/base/__init__.py
- app/model/schema/base/base.py
- app/model/schema/token.py
- app/routers/issuer/bond.py
- app/routers/issuer/ledger.py
- app/routers/issuer/position.py
- app/routers/issuer/settlement_issuer.py
- app/routers/issuer/share.py
- app/routers/issuer/token_holders.py
- app/utils/ledger_utils.py
- batch/indexer_dvp_delivery.py
- batch/indexer_issue_redeem.py
- batch/indexer_personal_info.py
- batch/indexer_position_bond.py
- batch/indexer_position_share.py
- batch/indexer_token_cache.py
- batch/indexer_token_holders.py
- batch/indexer_transfer.py
- batch/indexer_transfer_approval.py
- batch/processor_batch_register_personal_info.py
- batch/processor_create_utxo.py
- batch/processor_modify_personal_info.py
- docs/ibet_prime.yaml
- Related to https://github.com/BoostryJP/ibet-Prime/pull/749
- Improve `IssuedToken` model
> Improve IssuedToken schema

- app/routers/misc/freeze_log.py
- docs/ibet_prime.yaml
- Fixed an error in the response model setting of the RetrieveFreezeLog API.
> Fix response model

- app/model/db/idx_personal_info.py
- app/model/db/idx_position.py
- app/model/schema/personal_info.py
- app/routers/issuer/bond.py
- app/routers/issuer/position.py
- app/routers/issuer/share.py
- docs/ibet_prime.yaml
- migrations/versions/18506373ccd3_v25_3_0_feature_757.py
- tests/app/test_ledger_RetrieveLedgerHistory.py
- tests/app/test_sealed_tx_SealedTxRegisterPersonalInfo.py
- tests/app/test_token_holders_ListTokenHoldersPersonalInfo.py
- tests/batch/test_indexer_personal_info.py
- tests/batch/test_processor_update_token.py
- Close #757 
Ref: https://github.com/BoostryJP/ibet-Wallet-API/issues/1377
> Update primary key definitions

- batch/indexer_personal_info.py
- tests/batch/test_indexer_personal_info.py
> Fix duplicate key violation in Personal Info Indexer

- app/routers/issuer/account.py
- app/routers/issuer/bond.py
- app/routers/issuer/file.py
- app/routers/issuer/ledger.py
- app/routers/issuer/notification.py
- app/routers/issuer/position.py
- app/routers/issuer/settlement_issuer.py
- app/routers/issuer/share.py
- app/routers/issuer/token_common.py
- app/routers/issuer/token_holders.py
- app/routers/misc/bc_explorer.py
- app/routers/misc/e2e_messaging.py
- app/routers/misc/settlement_agent.py
> Optimize row count query performance

- app/main.py
- The existing `/healthcheck` API performs too many checks including Quorum connections and AWS Secret Manager validation. 
- This change provides a simpler healthcheck which can be used for `DEDICATED_SEALED_TX_MODE=1 mode.
- Close #768 
- Added lightweight DB healthcheck to root API
- Verified working correctly with local testing
> Add lightweight DB healthcheck to root API for `DEDICATED_SEALED_TX_MODE=1`

- batch/indexer_token_holders.py
- tests/batch/test_indexer_token_holders.py
- tests/contract_utils.py
Added ForceLock contract events as a processing target in the indexer_token_holders batch.
- Related to #778 
- Modified the indexer_token_holders batch to process ForceLock contract events
> Process force_lock event in indexer_token_holders

- .gitignore
Add *.egg-info/ to .gitignore to exclude egg-info files from version control
- None
- Add *.egg-info/ to .gitignore
> Add *.egg-info/ to .gitignore to exclude egg-info files from version control

- .gitignore
- app/utils/docs_utils.py
- docs/ibet_prime.yaml
This pull request includes updates to the `app/utils/docs_utils.py` file to improve error model handling and response generation, as well as extensive updates to the OpenAPI documentation in `docs/ibet_prime.yaml` to enhance schema definitions and flexibility.
- None
* **Response dictionary generation**: Updated `get_routers_responses` to include better type annotations and handle missing default responses gracefully.
* **Schema flexibility improvements**:
- Added `additionalProperties: true` to various object definitions to allow additional fields, enhancing schema flexibility.
> Enhance type hints and validation in error handling and OpenAPI responses

- batch/indexer_position_bond.py
- batch/indexer_position_share.py
This pull request refactors the notification handling logic for `LOCK` and `UNLOCK` events in the `batch/indexer_position_bond.py` and `batch/indexer_position_share.py` files. The changes simplify the code by consolidating event processing and database insertion logic, reducing redundancy, and introducing a unified structure for notification events.
- None
* Replaced individual calls to `__sink_on_lock_info_notification` and `__sink_on_unlock_info_notification` with appending structured event data to `notification_events`. This change applies to lock, force lock, unlock, and force unlock methods. 
* Added a new method `__insert_notification_events` to process and insert all events in `notification_events` into the database in a unified manner.
> Refactor notification handling by consolidating event processing

- batch/indexer_dvp_delivery.py
- batch/indexer_transfer_approval.py
This pull request refactors notification handling in `batch/indexer_dvp_delivery.py` and `batch/indexer_transfer_approval.py` to improve efficiency and maintainability.
Related to #802
* Added a `notification_events` list to store notification data for batch processing. 
* Replaced direct calls to `__sink_on_delivery_info_notification` with appending notification data to `notification_events` in methods like `__sync_delivery_confirmed` and `__sync_delivery_finished`.
* Introduced `__insert_notification_events` method to process and insert all notification events into the database in a single operation, improving efficiency.
* Cleared `notification_events` after processing in `sync_new_logs` to ensure no stale data remains. 
* Added a `notification_events` list for centralized storage of …
> Refactor notification handling by introducing event accumulation and batch insertion

- app/model/eth/__init__.py
- app/model/eth/wst.py
- app/utils/eth_contract_utils.py
- tests/app/model/eth/test_ERC20.py
- tests/app/model/eth/test_IbetWST.py
This pull request introduces several updates to the Ethereum-related modules and adds comprehensive test coverage for the ERC20 contract. 
- Part of #812
- Added ERC20 and IbetWST contract helpers. (`/app/model/eth`)
> Add ERC20/IbetWST model implementation and related tests

- app/model/db/__init__.py
- app/model/db/account.py
- app/model/db/ibet_wst.py
- app/model/db/token.py
- app/model/schema/token.py
- app/routers/issuer/bond.py
- app/routers/issuer/share.py
- app/utils/eth_contract_utils.py
- batch/processor_eth_wst_monitor_txreceipt.py
- batch/processor_eth_wst_send_tx.py
- docs/ibet_prime.yaml
- eth_config.py
- migrations/versions/1d859b48a7ad_v25_9_0_feature_812.py
- tests/app/test_bond_tokens_IssueBondToken.py
- tests/app/test_bond_tokens_ListBondOperationLogHistory.py
- tests/app/test_share_tokens_IssueShareToken.py
- tests/app/test_share_tokens_ListShareOperationLogHistory.py
- tests/app/utils/test_eth_asynccontract_utils.py
- tests/batch/test_processor_eth_wst_monitor_txreceipt.py
- tests/batch/test_processor_eth_wst_send_tx.py
This pull request introduces support for managing IbetWST transactions, including new database models, schema updates, transaction monitoring, and integration into existing token issuance workflows.
- Part of #812
* Added a new database model `EthIbetWSTTx` to manage Ethereum transactions for IbetWST, including transaction types (`IbetWSTTxType`), statuses (`IbetWSTTxStatus`), and versions (`IbetWSTVersion`). (`app/model/db/ibet_wst.py`)
* Introduced a utility method `get_finalized_block_number` in `eth_contract_utils.py` to fetch the latest finalized block number. (`app/utils/eth_contract_utils.py`)
* Updated `Token` model to include fields for IbetWST activation, version, deployment status, transaction ID, and contract address. (`app/model/db/token.py`)
* Added `activate_ibet_wst` field …
> Implement IbetWST transaction management and activation features

- app/exceptions.py
- app/routers/misc/ibet_wst.py
- docs/ibet_prime.yaml
- tests/app/test_ibet_wst_AcceptIbetWSTTrade.py
- tests/app/test_ibet_wst_BurnIbetWSTBalance.py
- tests/app/test_ibet_wst_CancelIbetWSTTrade.py
- tests/app/test_ibet_wst_GetIbetWSTBalance.py
- tests/app/test_ibet_wst_GetIbetWSTWhiteList.py
- tests/app/test_ibet_wst_RejectIbetWSTTrade.py
- tests/app/test_ibet_wst_RequestIbetWSTTrade.py
Added checks to ibet-WST related APIs.
- Close #832 
* Added `IbetWSTInsufficientBalanceError` and `ERC20InsufficientAllowanceError` to handle insufficient balance and allowance errors during token transfers. (`app/exceptions.py`)
* Introduced checks in various endpoints (`get_ibet_wst_balance`, `burn_ibet_wst_balance`, `accept_ibet_wst_trade`, etc.) to validate the existence of the IbetWST token and raise `HTTPException` with a 404 status if not found. (`app/routers/misc/ibet_wst.py`) [[1]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R196-R205) [[2]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R231-R239) [[3]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R477-R509)
> Add error handling for IbetWST token not found and insufficient balance/allowance

- app/model/eth/wst.py
- app/utils/eth_contract_utils.py
- batch/processor_eth_wst_monitor_txreceipt.py
- eth_config.py
- tests/app/model/eth/test_IbetWST.py
- tests/batch/test_processor_eth_wst_monitor_txreceipt.py
This PR optimizes the gas limit setting for Ethereum transactions for each transaction.
The limit setting for each transaction is set to a value approximately 1.2 times the results obtained in the test cases as a safety factor.
- Related to #812 
* Removed the global `ETH_TX_GAS_LIMIT` from `eth_config.py` and replaced it with specific gas values for each transaction type in `app/model/eth/wst.py`.
* Updated the gas limit for contract deployment in `deploy_contract` to 3,000,000 gas in `app/utils/eth_contract_utils.py`.
* Enhanced logging in `batch/processor_eth_wst_monitor_txreceipt.py` to include `gasUsed` in transaction success, failure, and finalization logs. [[1]](diffhunk://#diff-7711bbe44883be877362b4127aa3ba17ea790fe9c2cca884155238913e8ce7bcL117-R124) …
> Optimize gas settings for transaction processing

- app/model/db/__init__.py
- app/model/db/node.py
- app/routers/issuer/bond.py
- app/routers/issuer/common.py
- app/routers/issuer/share.py
- app/utils/eth_contract_utils.py
- app/utils/ibet_web3_utils.py
- batch/processor_monitor_block_sync_eth.py
- batch/processor_monitor_block_sync_ibet.py
- bin/healthcheck_processor.sh
- bin/run_processor.sh
- config.py
- docs/ibet_prime.yaml
- eth_config.py
- migrations/versions/15540246a906_v25_9_0_feature_836.py
- tests/app/test_common_ServiceHealthCheck.py
- tests/app/utils/test_eth_failover_http_provider.py
- tests/batch/test_processor_monitor_block_sync_eth.py
- tests/batch/test_processor_monitor_block_sync_ibet.py
This pull request introduces updates to the handling of Ethereum and ibet nodes, including the addition of a new `EthereumNode` model, failover logic for Ethereum node connections, and a dedicated processor for monitoring Ethereum node synchronization. It also refactors the existing ibet node synchronization processor for clarity and separation of concerns.
- Close #836 
* **New `EthereumNode` Model**: Added a new `EthereumNode` class to represent Ethereum node information, including endpoint URI, synchronization status, and priority. (`app/model/db/node.py`, [app/model/db/node.pyR38-R51](diffhunk://#diff-38442b0289d82793855e368a1df1d5ae616e6c39c8ae4054e8b674ad6b58db25R38-R51))
* **Failover Logic for Ethereum Node Connections**: Implemented `EthFailOverHTTPProvider` to enable failover …
> Add AsyncFailOverHTTPProvider and block synchronized monitoring processor for Ethereum node

- app/model/ibet/token.py
This pull request updates the error handling in the `app/model/ibet/token.py` file to account for a new exception type, `StaleDataError`, in addition to the existing `SAIntegrityError`.
- Close #828 
- Handle StaleDataError in token_cache commit process.
> Handle StaleDataError in database commit process

- app/model/db/idx_transfer.py
- app/model/schema/transfer.py
- app/utils/ibet_contract_utils.py
- batch/indexer_transfer.py
- batch/processor_create_utxo.py
- docs/ibet_prime.yaml
- tests/batch/test_indexer_transfer.py
- tests/batch/test_processor_create_utxo.py
This pull request introduces the concept of "Reallocation" as a new transfer event type.
- Close #852
* Added "Reallocation" as a new event type to `IDXTransferSourceEventType` and `TransferSourceEventType` enums in `app/model/db/idx_transfer.py` and `app/model/schema/transfer.py`. Updated relevant data models and schemas to handle this new event type. [[1]](diffhunk://#diff-8004d43cd0ab067d85d3e2ef24ecd1ab7b07dc3d22f3766a557cbcdf105e33e8R38) [[2]](diffhunk://#diff-8004d43cd0ab067d85d3e2ef24ecd1ab7b07dc3d22f3766a557cbcdf105e33e8L65-R82) [[3]](diffhunk://#diff-5509204cff742854c35f484566b14e3499429a995d887b547998105632ecfed9R44-R45) [[4]](diffhunk://#diff-5509204cff742854c35f484566b14e3499429a995d887b547998105632ecfed9L67-R95) [[5]](diffhunk://#diff-5509204cff742854c35f484566b14e3499429a995d …
> Add support for reallocation events in transfer processing

- README.md
- README_JA.md
- docker-compose.yml
This pull request updates the PostgreSQL version used across the project from 16 to 17, ensuring consistency in documentation and configuration files.
- Close #856 
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L26-R26): Updated the PostgreSQL version in the dependencies section from 16 to 17.
* [`README_JA.md`](diffhunk://#diff-f271b36948d7c29cd89eec7d160e57e411e28bd496449f272c70df1ff4e5f32cL27-R27): Updated the PostgreSQL version in the dependencies section from 16 to 17.
* [`docker-compose.yml`](diffhunk://#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3L3-R3): Updated the PostgreSQL Docker image version from 16 to 17.
> Support PostgreSQL 17

- app/model/db/ibet_wst.py
- app/model/eth/wst.py
- app/utils/eth_contract_utils.py
- batch/processor_eth_wst_monitor_txreceipt.py
- batch/processor_eth_wst_send_tx.py
- migrations/versions/b8410588fcb8_v25_9_0_feature_890.py
- tests/app/model/eth/test_ERC20.py
- tests/app/model/eth/test_IbetWST.py
- tests/app/utils/test_eth_asynccontract_utils.py
- tests/batch/test_processor_eth_wst_monitor_txreceipt.py
- tests/batch/test_processor_eth_wst_send_tx.py
This pull request introduces changes to improve how Ethereum transaction nonces are handled and tracked throughout the application, especially for IbetWST-related transactions. The main focus is to ensure that both the transaction hash and the nonce are returned and stored for relevant operations, enhancing traceability and reliability when interacting with the Ethereum network.
- Close #890 
**Nonce Handling and Propagation**
- Updated multiple methods in `app/model/eth/wst.py` and `app/utils/eth_contract_utils.py` to return both the transaction hash and the nonce as a tuple, instead of just the transaction hash. This affects all major transaction-related methods, such as minting, burning, transferring, and contract deployment. [[1]](diffhunk://#diff-3c09b1dc5d5811dd5975d55bebb8540a3543e2 …
> Add transaction nonce handling in IbetWST transactions

- README.md
- README_JA.md
- app/main.py
- app/model/db/dvp.py
- app/model/db/idx_dvp_delivery.py
- app/routers/misc/settlement_agent.py
- batch/indexer_dvp_delivery.py
- config.py
- migrations/versions/2057c79e5849_v25_9_0_feature_902.py
- tests/app/test_settlement_agent_ChangeDVPAgentAccountPassword.py
- tests/app/test_settlement_agent_CreateDVPAgentAccount.py
- tests/app/test_settlement_agent_DeleteDVPAgentAccount.py
- tests/app/test_settlement_agent_ListAllDVPAgentAccounts.py
- tests/app/test_settlement_agent_ListAllDVPAgentDeliveries.py
- tests/app/test_settlement_agent_UpdateDVPAgentDelivery.py
- tests/batch/test_indexer_dvp_delivery.py
This pull request introduces a new "Dedicated DVP Agent Mode" to the application, enabling operation as a dedicated DvP (Delivery versus Payment) agent server.
None
**Dedicated DVP Agent Mode support:**
* Added `DEDICATED_DVP_AGENT_MODE` and `DEDICATED_DVP_AGENT_ID` environment variables, and updated application startup logic to support running as a dedicated DvP agent server. [[1]](diffhunk://#diff-990f7e4140fab1ad82afc787505090b64d4024e63a891405cd9085e7e6b249ddR67) [[2]](diffhunk://#diff-990f7e4140fab1ad82afc787505090b64d4024e63a891405cd9085e7e6b249ddR189-R192) [[3]](diffhunk://#diff-117426151e93a626f8b46bfdb3a95b3f4a62e5f4dd6e65975a7c50759bf04482L349-R371)
* Updated API endpoints in `settlement_agent.py` to filter and operate on DVP agent accounts and deliveries by `dedicated_agent_id` …
> Add dedicated DVP agent mode configuration and routing
