BoostryJP/ibet-Prime

app/model/blockchain/personal_info.py, batch/processor_modify_personal_info.py
https://github.com/BoostryJP/ibet-Prime/pull/252 remain
```
[-bash ibet-Prime]$ grep -R 'call()' * | grep -v tests
app/utils/contract_utils.py:            result = _function(*args).call()
app/model/blockchain/personal_info.py:            call()
batch/processor_modify_personal_info.py:                        call()
batch/processor_modify_personal_info.py:            call()
[-bash ibet-Prime]$ 
```
=> feat: backward compatible contract calls(remain)

bin/run_server.sh
close #323 
---
1.
I wondered that ```config.py``` should validate environment variables and changed only script file.
2.
I noticed that ```config.py``` can be made more secure to avoid using global variable.
```python
def ConfigLoader():
self: Dict = {}
self.__setitem__(SERVER_NAME, "ibet-Prime")
self.__setitem__(APP_ENV, os.environ.get('APP_ENV') or "local")
self.__setitem__(NETWORK, os.environ.get("NETWORK") or "IBET")
...
def get(key: str):
nonlocal self
return self.__getitem__(key)
return get
get = ConfigLoader()
```
and in other file, variables can be read like below.
```python
import config
from config import SERVER_NAME
config.get(SERVER_NAME)
```
=> feat: Validate environment variables at server startup

app/exceptions.py, app/main.py, app/model/blockchain/e2e_messaging.py, app/model/blockchain/exchange.py, app/model/blockchain/personal_info.py, app/model/blockchain/token.py, app/model/blockchain/token_list.py, app/routers/bond.py, app/routers/e2e_messaging.py, app/routers/share.py, app/utils/contract_error_code.py, app/utils/contract_utils.py, app/utils/docs_utils.py, batch/processor_auto_transfer_approval.py, batch/processor_bulk_transfer.py, batch/processor_update_token.py, tests/model/blockchain/test_PersonalInfo.py, tests/model/blockchain/test_exchange_IbetSecurityTokenEscrow.py, tests/model/blockchain/test_token_IbetShare.py, tests/model/blockchain/test_token_IbetStraightBond.py, tests/model/blockchain/test_token_list.py, tests/test_app_routers_bond_transfer_approvals_{token_Address}_{id}_POST.py, tests/test_app_routers_share_transfer_approvals_{token_Address}_{id}_POST.py, tests/test_batch_processor_auto_transfer_approval.py, tests/test_utils_contract_utils.py
#329 
1. Added ContractRevertError as custom exception.
When you send transaction and revert is happened, contract_util inspects the reason of revert and raises reason with ContractRevertError.
If DB fails in sending transaction, SendTransactionError is raised as it is now.
2. In online API, added ContractRevertError to responses which API may return.
Fixed API documents.
For back compatible, ContractRevertError is returned with 400, same way as SendTransactionError.
(FastAPI in this repository uses OpenAPI 3.0.2. In 3.10.0, documents would be more understandable.)
URL: https://fastapi.tiangolo.com/tutorial/schema-extra-example/#body-with-multiple-examples:~:text=would%20look%20like%3A-,Technical%20Details,%C2%B6,-Warning 
3. When you use an endpoint about approveTransfer or run batch …
=> feat: retrieving message from error code to tell where logic error occurs in contract enhancement

app/model/db/idx_personal_info.py, app/routers/bond.py, app/routers/ledger.py, app/routers/share.py, app/utils/ledger_utils.py, batch/indexer_personal_info.py, batch/processor_modify_personal_info.py, tests/test_app_routers_bond_tokens_{token_address}_holders_GET.py, tests/test_app_routers_bond_tokens_{token_address}_holders_{account_address}_GET.py, tests/test_app_routers_bond_tokens_{token_address}_holders_{account_address}_personal_info_POST.py, tests/test_app_routers_bond_tokens_{token_address}_personal_info_POST.py, tests/test_app_routers_ledger_{token_address}_details_data_{data_id}_GET.py, tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py, tests/test_app_routers_share_tokens_{token_address}_holders_GET.py, tests/test_app_routers_share_tokens_{token_address}_holders_{account_address}_GET.py, tests/test_app_routers_share_tokens_{token_address}_holders_{account_address}_personal_info_POST.py, tests/test_app_routers_share_tokens_{token_address}_personal_info_POST.py
Close #335 
----
PersonalInfo is transmitted through the following 3 channels.
1. ibet-Prime Outside(REST API) => ibet-Prime Inside(DB)
2. ibet-Prime Inside(DB) <=> ibet-Network
3. ibet-Prime Inside(DB) => ibet-Prime Outside(REST-API)
So I revised DB model/Contract util/REST-API.
I fixed DB model(not schema).
Now default_value is automatically set to personal_information.
https://github.com/BoostryJP/ibet-Prime/blob/1d7a9b889a8953bdab5aa633ede612673e93fa69/app/model/db/idx_personal_info.py#L52-L78
I added default_value argument as None explicitly to all Create/Update methods.
I checked following 5 endpoints and fixed 1 endpoint.
(This is referred to in Issue #355 .)
All but one is currently allowed to use null value in PersonalInfo.
```s
Checked
Fixed
```
---
<details><pre><code>
1. …
=> fix: An error occurs in the ledger API when personal information is null

Dockerfile, README.md, requirements.lock, requirements.txt, tests/Dockerfile, tests/requirements.txt
Upgrade python from 3.8 to 3.10 latest.
As part of this upgrade, we are upgrading the following modules to the latest versions
- psycopg2-binary
- pytest
Also, currently, the version of SQLAlchemy was not fixed, so it was fixed.
=> feat: upgrade python

app/routers/position.py, tests/test_app_routers_positions_{account_address}_GET.py, tests/test_app_routers_positions_{account_address}_{token_address}_GET.py
=> fix: Excluding former holders in holders endpoint

app/model/schema/__init__.py, app/model/schema/index.py, app/routers/index.py, tests/test_app_routers_block_number_GET.py
=> feat: endpoint to get the current block number

app/routers/bond.py, app/routers/position.py, app/routers/share.py, app/utils/contract_utils.py, tests/test_app_routers_bond_tokens_{token_address}_holders_GET.py, tests/test_app_routers_positions_{account_address}_GET.py, tests/test_app_routers_share_tokens_{token_address}_holders_GET.py
Close #369 
- Added query param so as to retrieve former holders.
GET: `/bond/tokens/{token_address}/holders`
GET: `/share/tokens/{token_address}/holders`
- added `include_former_holder` param.
GET: `/positions/{account_address}`
- added `include_former_position` param.
following GET: `/bond/tokens/{token_address}/holders` example.
=> feat: add query param to position API for retrieving former holders

app/model/db/batch_register_personal_info.py, app/model/schema/batch_issue_redeem.py, app/model/schema/personal_info.py, app/routers/bond.py, app/routers/share.py, tests/test_app_routers_bond_tokens_{token_address}_additional_issue_batch_GET.py, tests/test_app_routers_bond_tokens_{token_address}_personal_info_batch_GET.py, tests/test_app_routers_bond_tokens_{token_address}_personal_info_batch_{batch_id}_GET.py, tests/test_app_routers_bond_tokens_{token_address}_redeem_batch_GET.py, tests/test_app_routers_share_tokens_{token_address}_additional_issue_batch_GET.py, tests/test_app_routers_share_tokens_{token_address}_personal_info_batch_GET.py, tests/test_app_routers_share_tokens_{token_address}_personal_info_batch_{batch_id}_GET.py, tests/test_app_routers_share_tokens_{token_address}_redeem_batch_GET.py
Add new APIs: List personal information batch registration uploads
- GET: /bond/tokens/{token_address}/personal_info/batch
- GET: /share/tokens/{token_address}/personal_info/batch
In addition, various improvements were made to related functions.
=> feat: Add new APIs - list personal info batch registration uploads

app/exceptions.py, app/model/blockchain/token.py, batch/processor_batch_issue_redeem.py, batch/processor_rotate_e2e_messaging_rsa_key.py, batch/processor_scheduled_events.py, tests/test_batch_processor_batch_issue_redeem.py, tests/test_batch_processor_rotate_e2e_messaging_rsa_key.py, tests/test_batch_processor_scheduled_events.py
Close: #380 
- Added contract revert error handling to batches which does not have it.
- Added unit tests for logging error.
=> fix: add error handling for contract revert error

app/model/schema/notification.py, batch/indexer_transfer_approval.py, batch/processor_batch_issue_redeem.py, batch/processor_scheduled_events.py, tests/test_app_routers_docs_GET.py, tests/test_app_routers_notifications_GET.py, tests/test_batch_indexer_transfer_approval.py, tests/test_batch_processor_batch_issue_redeem.py, tests/test_batch_processor_scheduled_events.py
Close #382 
- Added "token_address" attribute to notification metainfo which specific token is related to.
- Added `optional` to notification types which is introduced before v22.6.
- Renamed schema models from Metainfo to Meta**I**nfo.
> - トークン軸の通知に"token_address"属性を追加しました。
>   - v22.6以前に存在した通知タイプへは`optional`を追加しました。
> - MetainfoからMeta**I**nfoにリネームしました。
=> feat: Add token_address attribute to notification metainfo

app/model/schema/batch_issue_redeem.py, app/model/schema/personal_info.py, app/routers/bond.py, app/routers/share.py
**Fixed only docs**
- Add example value for `BatchRegisterPersonalInfoUploadResponse` / `BatchIssueRedeemUpload` .
- Set deprecated flag True to modify_holder_personal_info endpoint which has been already deprecated.
e.g.)
- Before
- ![スクリーンショット 2022-09-14 9 30 51](https://user-images.githubusercontent.com/15183665/190033408-a18af198-f0c0-4f16-a830-36887d1ede0c.png)
- ![スクリーンショット 2022-09-14 9 32 21](https://user-images.githubusercontent.com/15183665/190033443-ae62ffeb-2190-464f-a384-0017ccb44c16.png)
- After
- "Deprecated" added
- Response example added
=> fix: openapi document

app/model/schema/__init__.py, app/model/schema/token_holders.py, app/routers/token_holders.py, tests/test_app_routers_token_holders_{token_address}_GET.py
=> feat: add TokenHolderCollection list API

app/model/schema/token.py, app/model/schema/types.py, tests/test_app_routers_share_tokens_POST.py, tests/test_app_routers_share_tokens_{token_address}_POST.py
=> feat: allow empty input

batch/indexer_issue_redeem.py, batch/indexer_position_bond.py, batch/indexer_position_share.py, batch/indexer_transfer.py, batch/indexer_transfer_approval.py, tests/test_batch_indexer_issue_redeem.py, tests/test_batch_indexer_position_bond.py, tests/test_batch_indexer_position_share.py, tests/test_batch_indexer_transfer.py, tests/test_batch_indexer_transfer_approval.py
Close #388
- Changed indexer batch logics to keep ABI data in memory and not to fetch ABI data from DB each time.
- Added Unit tests.
> ABIデータをメモリ内に保持し毎回ABIデータをDBから取得しないようにindexerバッチのロジックを変更しました。
> ユニットテストを追加しました。
=> feat: avoid to fetch ABI data from DB in indexer batch every cycle

app/model/blockchain/token.py
Related to: #401
Close : #426 
The following errors were frequently occurring in the DB when creating a cache of token attributes, and have been corrected to suppress them.
```
2022-11-21 09:20:43.727 UTC [752019] ERROR:  duplicate key value violates unique constraint "token_cache_pkey"
2022-11-21 09:20:43.727 UTC [752019] DETAIL:  Key (token_address)=(0x2ff71d6769773B8E7cB368444FdD0678f2214E5c) already exists.
```
=> feat: Suppress unique constraint errors

bin/run_server.sh
Close: #430 
Changed the limit_request_line setting for gunicorn to unlimited.
=> feat: unlimited request line size

app/routers/token_holders.py
=> fix: Change to use Web3Wrapper

app/main.py, app/routers/e2e_messaging.py, app/routers/file.py, app/routers/index.py, app/routers/ledger.py, app/routers/position.py, app/routers/token_holders.py
=> feat: Add openapi tag descriptions

app/main.py, app/routers/account.py, app/routers/bc_explorer.py, app/routers/bond.py, app/routers/common.py, app/routers/e2e_messaging.py, app/routers/file.py, app/routers/ledger.py, app/routers/notification.py, app/routers/position.py, app/routers/share.py, app/routers/token_holders.py, app/utils/fastapi.py, config.py, docker-compose.yml, requirements.lock, requirements.txt
=> feat: Omit response validation in all API endpoints

app/routers/ledger.py
fix: #452 
- Removed unnecessary `json_response()` func in ledger API.
- Checked that the unit test with `RESPONSE_VALIDATION_MODE=0` is passed.
=> fix: Omit response validation in all API endpoints

app/model/blockchain/exchange.py, app/model/blockchain/token.py, app/model/blockchain/tx_params/ibet_security_token.py, app/model/blockchain/tx_params/ibet_security_token_escrow.py, app/model/blockchain/tx_params/ibet_share.py, app/model/blockchain/tx_params/ibet_straight_bond.py, app/model/schema/__init__.py, app/model/schema/token.py, app/routers/bond.py, app/routers/share.py, batch/processor_batch_issue_redeem.py, batch/processor_bulk_transfer.py, batch/processor_scheduled_events.py, batch/processor_update_token.py, tests/model/blockchain/test_exchange_IbetSecurityTokenEscrow.py, tests/model/blockchain/test_token_IbetShare.py, tests/model/blockchain/test_token_IbetStraightBond.py, tests/test_app_routers_bond_transfer_approvals_{token_Address}_{id}_POST.py, tests/test_app_routers_bond_transfers_POST.py, tests/test_app_routers_share_transfer_approvals_{token_Address}_{id}_POST.py, tests/test_app_routers_share_transfers_POST.py, tests/test_batch_processor_create_utxo.py
=> feat: Separate the dataclass of the contract from the request Schema of the API

app/model/schema/__init__.py, app/model/schema/token.py, app/routers/bond.py, app/routers/position.py, app/routers/share.py, tests/test_app_routers_bond_lock_events_GET.py, tests/test_app_routers_share_lock_events_GET.py
Close: #479 
- [NEW] GET: `/bond/tokens/{token_address}/lock_events`
- [NEW] GET: `/share/tokens/{token_address}/lock_events`
- Added lock events endpoint
=> feat: add lock events endpoint to token API

batch/indexer_token_holders.py, batch/processor_create_utxo.py, tests/test_batch_indexer_token_holders.py, tests/test_batch_processor_create_utxo.py
Close: #480 
- Added `argument_filter` to getLogs function in 2 batches.
- `indexer_Token_Holders.py`
- `processor_create_utxo.py`
- (There were few getLogs to which filters could be added...)
=> feat: add argument filter to batch

batch/indexer_token_holders.py, tests/test_batch_indexer_token_holders.py
=> fix: avoid storing non-holders in TokenHolders batch

batch/indexer_token_holders.py, tests/test_batch_indexer_token_holders.py
=> fix: set previous locked balance when checkpoint is used

poetry.lock, pyproject.toml
Bumps [requests](https://github.com/psf/requests) to 2.31.0.
The version of `requets` currently in use has the following vulnerabilities, so I would like to upgrade it.
https://github.com/advisories/GHSA-j8r2-6x86-q33q
=> Bump requests from 2.30 to 2.31

poetry.lock, pyproject.toml
Upgraded fastapi.
This version upgrade is expected to reduce the high CPU load at startup.
Ref: https://github.com/tiangolo/fastapi/discussions/8609#discussioncomment-5811943
=> Bump fastapi v0.96

app/model/blockchain/token.py, app/model/db/__init__.py, app/model/db/token_update_operation_log.py, app/model/schema/__init__.py, app/model/schema/token.py, app/routers/bond.py, app/routers/share.py, cmd/explorer/src/connector/__init__.py, migrations/versions/8ed94523e21c_v23_9_0_feature_529.py, tests/model/blockchain/test_token_IbetShare.py, tests/model/blockchain/test_token_IbetStraightBond.py, tests/test_app_routers_bond_tokens_POST.py, tests/test_app_routers_bond_tokens_{token_address}_POST.py, tests/test_app_routers_bond_tokens_{token_address}_history_GET.py, tests/test_app_routers_share_tokens_POST.py, tests/test_app_routers_share_tokens_{token_address}_POST.py, tests/test_app_routers_share_tokens_{token_address}_history_GET.py
Close: #529 
----
- API
- GET: `/bond/{token_address}/history`
- Changed to use **token_update_operation_log** data for response data
- POST: `/bond`
- Changed to store **token_update_operation_log** data as Issue data
- POST: `/bond/{token_address}`
- Changed to store **token_update_operation_log** data as Update data
- GET: `/share/{token_address}/history`
- Changed to use **token_update_operation_log** data for response data
- POST: `/share`
- Changed to store **token_update_operation_log** data as Issue data
- POST: `/share/{token_address}`
- Changed to store **token_update_operation_log** data as Update data
- DB
- `update_token.original_contents`: column deleted
- `token_update_operation_log`: table added
=> Add token update operation log for audit

Dockerfile, app/model/schema/batch_issue_redeem.py, app/model/schema/personal_info.py, app/routers/bond.py, app/routers/share.py, tests/Dockerfile, tests/test_app_routers_bond_tokens_{token_address}_additional_issue_batch_{batch_id}_GET.py, tests/test_app_routers_bond_tokens_{token_address}_redeem_batch_{batch_id}_GET.py, tests/test_app_routers_share_tokens_{token_address}_additional_issue_batch_{batch_id}_GET.py, tests/test_app_routers_share_tokens_{token_address}_redeem_batch_{batch_id}_GET.py
Close: #535 
- Added `personal_information` attribute to the response of API following.
- GET: `/bond/tokens/{token_address}/additional_issue/batch/{batch_id}`
- GET: `/bond/tokens/{token_address}/redeem/batch/{batch_id}`
- GET: `/share/tokens/{token_address}/additional_issue/batch/{batch_id}`
- GET: `/share/tokens/{token_address}/redeem/batch/{batch_id}`
- `personal_information` attribute added only to the response of APIs that authenticate by `issuer_address` in the HTTP Header.
=> Add `personal_information` field to API response of list all batch redeem/issue records

batch/processor_scheduled_events.py, tests/test_batch_processor_scheduled_events.py
=> Record token update operation caused by scheduled event as history

app/model/schema/transfer.py, app/routers/bond.py, app/routers/share.py, cmd/explorer/src/connector/__init__.py, tests/test_app_routers_bond_transfer_approvals_{token_address}_GET.py, tests/test_app_routers_share_transfer_approvals_{token_address}_GET.py
Related to: https://github.com/BoostryJP/ibet-Prime/issues/555
- Added `personal_information` to token transfer approval list API as well detailed API(implemented in #556).
=> Add `personal_information` to token transfer approval list API response

.pre-commit-config.yaml, Makefile, poetry.lock, pyproject.toml, tests/model/blockchain/test_token_IbetShare.py, tests/model/blockchain/test_token_IbetStraightBond.py
Updated third-party libraries.
=> Bump packages

app/model/schema/base/__init__.py, app/model/schema/base/base.py, app/model/schema/token.py, tests/test_app_routers_bond_tokens_{token_address}_POST.py
=> Allow setting empty str for `interest_payment_currency` and `redemption_value_currency` when updating bond token

app/model/db/bulk_transfer.py, app/model/schema/bulk_transfer.py, app/routers/bond.py, app/routers/share.py, batch/processor_bulk_transfer.py, migrations/versions/beb9a0e876f8_v24_3_0_feature_585.py, tests/test_app_routers_bond_bulk_transfer_{upload_id}_GET.py, tests/test_app_routers_share_bulk_transfer_{upload_id}_GET.py, tests/test_batch_processor_bulk_transfer.py
=> Retrieve the error reason that occurs during bulk transfer

app/model/schema/__init__.py, app/model/schema/base/__init__.py, app/model/schema/base/base.py, app/model/schema/token.py, app/routers/bond.py, app/routers/share.py, cmd/explorer/src/connector/__init__.py, tests/test_app_routers_bond_tokens_{token_address}_holders_GET.py, tests/test_app_routers_share_tokens_{token_address}_holders_GET.py
Close: #601 
- Added query parameter to following holders API in order to filter and sort holders list.
- GET: `/bond/tokens/{token_address}/holders`
- GET: `/share/tokens/{token_address}/holders`
=> Added filter and sort query of personal_info, balance or locked amount to token holders API

app/utils/ledger_utils.py, tests/test_utils_ledger_utils.py
=> Make it more precise about the value of `personal_info_not_registered`

app/model/__init__.py, app/model/db/__init__.py, app/model/db/idx_personal_info.py, app/model/schema/__init__.py, app/model/schema/personal_info.py, app/model/schema/token.py, app/model/schema/token_holders.py, app/routers/bond.py, app/routers/share.py, app/routers/token_holders.py, batch/indexer_personal_info.py, cmd/explorer/src/connector/__init__.py, docker-compose.yml, docs/ibet_prime.yaml, migrations/versions/0656c408ebbb_v24_6_0_feature_627.py, tests/test_app_routers_bond_tokens_{token_address}_history_GET.py, tests/test_app_routers_share_tokens_{token_address}_history_GET.py, tests/test_app_routers_token_holders_personal_info_GET.py, tests/test_app_routers_token_holders_personal_info_history_GET.py, tests/test_batch_indexer_personal_info.py
- close #627
- Also, search items and sort items for the existing API (ListTokenHoldersPersonalInfo) have been added.
- Additionally, on a related note, I made improvements to datetime string input and output.
```
API IF変更に関して、日本語 🇯🇵 で補足しておきます。
１）【変更】GET: /token/holders/personal_info
- 入力：検索項目の追加（created_from、created_to、modified_from、modified_to）
- https://github.com/BoostryJP/ibet-Prime/pull/628/files#diff-9e2327c7090e5fdd3df4edd2e35959df2be0c38196dee097fdfcc511aca5462bR49-R60
- "%Y-%m-%d %H:%M:%S" のフォーマットを強制するようにしている。
- それぞれのタイムゾーンでの日時を入力すれば良い（内部的に自動でUTCなどに変換されて処理される）。
- 入力：ソート項目の指定を可能にした（sort_item）。account_address, created, modified でのソートが可能。
- https://github.com/BoostryJP/ibet-Prime/pull/628/files#diff-9e2327c7090e5fdd3df4edd2e35959df2be0c38196dee097fdfcc511aca5462bR62-R64
- …
```
=> Add personal info history API

app/routers/ledger.py, tests/test_app_routers_ledger_{token_address}_history_{ledger_id}_GET.py
=> Fix the logic of __get_personal_info used in ledger history API

app/model/schema/__init__.py, app/model/schema/settlement.py, app/routers/issuer/settlement_issuer.py, app/routers/misc/settlement_agent.py, app/utils/docs_utils.py, docs/ibet_prime.yaml, tests/app/test_settlement_dvp_{exchange_address}_deliveries_GET.py, tests/app/test_settlement_dvp_{exchange_address}_delivery_{delivery_id}_GET.py
- There is a need to refer to personal information registered for issuers for buyers/sellers in DVP settlement.
- Add personal information to the API response items of delivery data.
=> Add buyer/seller personal information to DvP delivery data

batch/processor_monitor_block_sync.py, config.py, tests/batch/test_processor_monitor_block_sync.py
close #685 
- EXPECTED_BLOCKS_PER_SEC: 1 block/sec -> 0.1 block/sec
- Fixed an error in the calculation formula using EXPECTED_BLOCKS_PER_SEC.
=> Change the default value of EXPECTED_BLOCKS_PER_SEC

app/main.py, app/model/schema/__init__.py, app/model/schema/sealed_tx.py, app/routers/misc/sealed_tx.py, app/utils/sealedtx_utils.py, docs/ibet_prime.yaml, pyproject.toml, tests/app/test_sealed_tx_SealedTxRegisterPersonalInfo.py, tests/app/utils/generate_signature.py, tests/app/utils/test_sealed_tx_utils.py
close #689 
Add SealedTx feature 🚀 
- As a simple implementation, I decided to overwrite the data of PersonalInfo if it already exists. 
- Therefore, if there is a delay in reflecting on-chain information, it is possible that it may be overwritten again by the on-chain information. However, since it seems there are no use cases that utilize both on-chain and off-chain transactions, I have decided not to consider this for now.
=> Add SealedTx feature

app/model/schema/notification.py, batch/processor_bulk_transfer.py, docs/ibet_prime.yaml, tests/app/test_notifications_ListAllNotifications.py, tests/batch/test_processor_bulk_transfer.py
=> Add a token_address field to the Metainfo of BULK_TRANSFER_ERROR notification

app/model/schema/__init__.py, app/model/schema/bulk_transfer.py, app/routers/issuer/bond.py, app/routers/issuer/share.py, docs/ibet_prime.yaml, tests/app/test_bond_bulk_transfer_ListBondTokenBulkTransfers.py, tests/app/test_share_bulk_transfer_ListShareTokenBulkTransfers.py
=> Enable searching bulk transfer uploads by token address

app/model/schema/__init__.py, app/model/schema/account.py, app/model/schema/token_holders.py, app/routers/issuer/account.py, app/routers/issuer/token_holders.py, docs/ibet_prime.yaml, tests/app/test_accounts_ListAllChildAccount.py, tests/app/test_accounts_RetrieveChildAccount.py
=> Add search query and sort item for ChildAccount API

Makefile, app/model/db/__init__.py, app/model/db/idx_transfer.py, app/model/schema/__init__.py, app/model/schema/transfer.py, app/routers/issuer/bond.py, app/routers/issuer/position.py, app/routers/issuer/settlement_issuer.py, app/routers/issuer/share.py, app/routers/misc/settlement_agent.py, batch/indexer_transfer.py, docs/ibet_prime.yaml, migrations/versions/68f088d446c4_v24_12_0_feature_700.py, tests/app/model/blockchain/test_token_IbetShare.py, tests/app/model/blockchain/test_token_IbetStraightBond.py, tests/app/test_bond_transfers_ListBondTokenTransferHistory.py, tests/app/test_positions_ForceUnlock.py, tests/app/test_share_transfers_ListShareTokenTransferHistory.py, tests/batch/test_indexer_transfer.py
Close #700 
**DB**
- Added new message column with index to idx_transfer table, separate from existing JSON data field
**API**
- Detailed transfer data schema on Transfer List API to classify transfer data derived from Unlock events
```Python
class TransferBase(BaseModel):
transaction_hash: str
token_address: str
from_address: str
from_address_personal_information: Optional[PersonalInfo] = Field(...)
to_address: str
to_address_personal_information: Optional[PersonalInfo] = Field(...)
amount: int
block_timestamp: str
class Transfer(TransferBase):
source_event: Literal[TransferSourceEventType.Transfer] = Field(
description="Source Event"
)
data: None = Field(description="Event data")
class UnlockData(BaseModel):
message: Literal[
"garnishment",
"inheritance",
"force_unlock",
]
class …
```
=> Refine transfer data schema to classify transfer data derived from Unlock events

app/exceptions.py, app/routers/issuer/bond.py, app/routers/issuer/share.py, batch/processor_batch_register_personal_info.py, cmd/explorer/src/connector/__init__.py, config.py, docs/ibet_prime.yaml, tests/app/test_bond_personal_info_InitiateBondTokenBatchPersonalInfoRegistration.py, tests/app/test_bond_personal_info_RegisterBondTokenHolderPersonalInfo.py, tests/app/test_share_personal_info_InitiateShareTokenBatchPersonalInfoRegistration.py, tests/app/test_share_personal_info_RegisterShareTokenHolderPersonalInfo.py, tests/batch/test_processor_register_personal_info.py
- Add error handling and validation for posted personal info length
=> Add error handling and validation for posted personal info length

app/routers/issuer/account.py, app/utils/docs_utils.py, docs/ibet_prime.yaml, tests/app/test_accounts_CreateChildAccount.py, tests/app/test_accounts_CreateChildAccountInBatch.py, tests/app/test_accounts_UpdateChildAccount.py
- Add validation for posted personal info length to child account API
- Updated the API docs to describe the details of `BatchPersonalInfoRegistrationValidationError`
=> Add validation for posted personal info length to child account API

app/model/db/batch_register_personal_info.py, app/model/schema/notification.py, app/routers/issuer/bond.py, app/routers/issuer/share.py, batch/processor_batch_register_personal_info.py, docs/ibet_prime.yaml, migrations/versions/02791d34c2ad_v25_3_0_feature_736.py, tests/app/test_bond_personal_info_InitiateBondTokenBatchPersonalInfoRegistration.py, tests/app/test_notifications_ListAllNotifications.py, tests/app/test_share_personal_info_InitiateShareTokenBatchPersonalInfoRegistration.py, tests/batch/test_processor_register_personal_info.py
close #736 
Add `token_address` to the metainfo of the `BatchRegisterPersonalInfoError `
- Do not set it for past records.  
- Make it optional in the schema definition as well.  
I chose the approach of adding a field to the upload TBL.
=> Add token_address attribute to notification metainfo

app/main.py, app/model/schema/__init__.py, app/model/schema/token.py, app/routers/issuer/token_common.py, docs/ibet_prime.yaml, tests/app/test_token_common_ListAllIssuedTokens.py
=> Add ListAllIssuedTokens API

README.md, README_JA.md, app/utils/contract_utils.py, batch/indexer_block_tx_data.py, batch/indexer_token_holders.py, batch/processor_batch_issue_redeem.py, batch/processor_create_utxo.py, batch/processor_dvp_async_tx.py, batch/processor_generate_rsa_key.py
In `send_transaction` of `AsyncContractUtils`, `psycopg` was still being used during table locks. This has now been replaced with `asyncpg`, making it consistent with other online processes.  
- **Note:** The non-async version of `ContractUtils` will continue to use `psycopg`.  
Various other improvements were also made.
=> Change the database connection in AsyncContractUtils to use asyncpg

app/routers/issuer/bond.py, app/routers/issuer/share.py
- Related to #763 
- Optimized row count query performance of multiple joined statement
- Target APIs are as follows:
- GET: `/bond/tokens/{token_address}/holders`
- GET: `/share/tokens/{token_address}/holders`
=> Optimize row count query performance of multiple joined statement

app/model/db/idx_personal_info.py, app/model/db/idx_position.py, migrations/versions/40e3e7206fbc_v25_3_0_fix_763_2.py
- Additional fix related to 
- #763 
- #764 
- Added SQL INDEX to optimize follow APIs
- GET: `/bond/tokens/{token_address}/holders`
- GET: `/share/tokens/{token_address}/holders`
=> Add SQL INDEX to optimize token holders API performance

app/main.py, batch/__init__.py, batch/indexer_block_tx_data.py, batch/indexer_dvp_delivery.py, batch/indexer_e2e_messaging.py, batch/indexer_issue_redeem.py, batch/indexer_personal_info.py, batch/indexer_position_bond.py, batch/indexer_position_share.py, batch/indexer_token_cache.py, batch/indexer_token_holders.py, batch/indexer_transfer.py, batch/indexer_transfer_approval.py, batch/processor_batch_create_child_account.py, batch/processor_batch_issue_redeem.py, batch/processor_batch_register_personal_info.py, batch/processor_bulk_transfer.py, batch/processor_create_ledger.py, batch/processor_create_utxo.py, batch/processor_dvp_async_tx.py, batch/processor_generate_rsa_key.py, batch/processor_modify_personal_info.py, batch/processor_monitor_block_sync.py, batch/processor_rotate_e2e_messaging_rsa_key.py, batch/processor_scheduled_events.py, batch/processor_update_token.py
When a Python process runs for an extended period, unused memory may not be released and returned to the OS.
To address this, I have implemented periodic execution of malloc_trim(0) to free up unused heap memory as much as possible.
=> Release free memory back to the OS with malloc_trim

app/model/db/ledger.py, app/routers/issuer/ledger.py
For ledger data sourced from the database, the `account_address` is set to `""`. Additionally, inconsistencies in the `data_type` setting of `LedgerDetailsTemplate` may cause it to have values other than `"DB"`.  
We detected an issue where contract access fails during the latest ledger personal information request due to this inconsistency. To address this, I have implemented a control logic to ensure the system can handle data inconsistencies in `LedgerDetailsTemplate`.
- None
I have added control logic to `RetrieveLedgerHistory` API to handle data inconsistencies in `LedgerDetailsTemplate`. 
This ensures that the process remains stable even when inconsistencies occur.
=> Handle Data Inconsistencies in LedgerDetailsTemplate

app/model/db/scheduled_events.py, app/model/schema/__init__.py, app/model/schema/scheduled_events.py, app/routers/issuer/bond.py, app/routers/issuer/share.py, app/routers/issuer/token_common.py, batch/processor_scheduled_events.py, docs/ibet_prime.yaml, migrations/versions/e1f6370e8197_v25_6_0_feature_772.py, tests/app/test_bond_scheduled_events_DeleteScheduledBondTokenUpdateEvent.py, tests/app/test_bond_scheduled_events_ListAllScheduledBondTokenUpdateEvents.py, tests/app/test_bond_scheduled_events_RetrieveScheduledBondTokenUpdateEvent.py, tests/app/test_share_scheduled_events_DeleteScheduledShareTokenUpdateEvent.py, tests/app/test_share_scheduled_events_ListAllScheduledShareTokenUpdateEvents.py, tests/app/test_share_scheduled_events_RetrieveScheduledShareTokenUpdateEvent.py, tests/app/test_token_common_ListAllScheduledEvents.py, tests/batch/test_processor_scheduled_events.py
I have modified the functionality so that it is possible to manage the soft/logical deletion state for ScheduledEvents.
In the soft deletion state, it is controlled so that it is not subject to batch processing.
- Close #772
- I added a field called `is_soft_deleted` to the TBL.
- I made it possible to specify a soft delete parameter in the delete API. If the parameter is not set, the event data will be physically deleted.
- For the event data extraction process in batch processing, I modified the query so that data in a logical deletion state is not extracted.
=> Add a Soft Delete Feature to Scheduled Events

app/model/schema/__init__.py, app/model/schema/position.py, app/model/schema/transfer.py, app/routers/issuer/position.py, docs/ibet_prime.yaml, tests/app/test_positions_ForceLock.py, tests/app/test_positions_ForceUnlock.py
Currently, the message registered in the contract during ForceLock/ForceUnlock was fixed. This update allows selecting and registering a custom message.
The selectable messages are: “garnishment”, “Inheritance” and “force_lock / force_unlock”
- Related to #777
- Added a "message" parameter to the input fields of the ForceLock/ForceUnlock API.
- By default, "force_lock" or "force_unlock" will be set.
=> Allow setting a message for ForceLock/ForceUnlock

batch/processor_monitor_block_sync.py
This pull request updates the `__set_node_info` method in the `batch/processor_monitor_block_sync.py` file to explicitly disable retry logic for the `AsyncHTTPProvider`. This change ensures that no automatic retries occur when interacting with the specified `endpoint_uri`.
- Close #785
* [`batch/processor_monitor_block_sync.py`](diffhunk://#diff-cfc8127f2cced3cfd40298e76279b3e5b9e038a90b2104280b2f76be31c878baL122-R128): Modified the initialization of `AsyncHTTPProvider` within the `__set_node_info` method to set `exception_retry_configuration=None`, explicitly disabling retry logic.
=> Disable retry logic in AsyncHTTPProvider for web3 connection of processor_monitor_block_sync

batch/indexer_transfer.py, tests/batch/test_indexer_transfer.py
Updated `batch/indexer_transfer.py` to Handle generic exceptions in parsing message data and updated test for invalid data schema
- Close #784 
* [`batch/indexer_transfer.py`](diffhunk://#diff-9d49fe1a54b4cf0765a1e08e08dac073d05acc075bf8c50cf7eeab99b7c96855R347-R349): Added a generic exception handler in the `__sink_on_transfer` method to handle any unexpected exceptions, for the cases where the `data` and `message` to be set invalid JSON value such as "null".
=> Handle generic exceptions in indexer_transfer and update test for invalid data schema

.github/workflows/auto-assign.yml, .github/workflows/pr.yml
This pull request updates the versions of several GitHub Actions used in the repository's workflows to ensure compatibility and stability. The updates include pinning specific commit SHAs or upgrading to newer versions.
- None
- `.github/workflows/auto-assign.yml`: 
- Updated `kentaro-m/auto-assign-action` to a specific commit SHA (`f4648c0a9fdb753479e9e75fc251f507ce17bb7e`) for better version control and stability.
- `.github/workflows/pr.yml`: 
- Upgraded `astral-sh/ruff-action` from `v1` to `v3` to use the latest features and improvements.
- Updated `MishaKav/pytest-coverage-comment` to a specific commit SHA (`13d3c18e21895566c746187c9ea74736372e5e91`), corresponding to version `v1.1.54`, for enhanced functionality and reliability.
=> Update action versions in GitHub workflows for auto-assign and PR checks

app/log.py, app/main.py, app/utils/o11y_utils.py, batch/__init__.py, batch/utils/batch_log.py, config.py, pyproject.toml, uv.lock
Added environment variable configurations to output and send performance-related metrics. This enables continuous profiling and tracing capabilities that can be toggled on/off as needed.
- Close #799 
- Added environment variable settings for performance metrics output and transmission
- `PROFILING_MODE`: Set to `1` to enable performance metrics setup for both server and batch processes at startup
- `PYROSCOPE_SERVER_URL`: Set the URL of the Pyroscope server
- `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`: Set the URL of the OTEL trace data destination server
- Note: This variable is used internally by `opentelemetry-sdk`, so it's not included in `config.py` as an ibet-wallet-api configuration
- [-] I have added tests where necessary.
- [-] I have updated the documentation where necessary.
=> Add OpenTelemetry and Pyroscope setup for profiling and monitoring

README.md, README_JA.md, app/main.py, docs/ibet_prime.yaml, package-lock.json, pyproject.toml, uv.lock
This pull request updates the version number of the `ibet-Prime` project from `25.6` to `25.9` across multiple files to ensure consistency in documentation, metadata, and application configuration.
None
Version updates:
* `README.md` and `README_JA.md`: Updated the version badge to reflect the new version `25.9`. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L8-R8) [[2]](diffhunk://#diff-f271b36948d7c29cd89eec7d160e57e411e28bd496449f272c70df1ff4e5f32cL8-R8)
* [`app/main.py`](diffhunk://#diff-990f7e4140fab1ad82afc787505090b64d4024e63a891405cd9085e7e6b249ddL131-R131): Updated the `FastAPI` application version to `25.9`.
* [`docs/ibet_prime.yaml`](diffhunk://#diff-e54863847006bb647956a60aebd43bf13e3ce8bf1a59539d4e8692da6bed254eL5-R5): Updated the …
=> Bump version from 25.6 to 25.9

batch/indexer_dvp_delivery.py, tests/batch/test_indexer_dvp_delivery.py
This pull request includes a small change to the `batch/indexer_dvp_delivery.py` file. The change ensures that the `notification_events` attribute is reset to an empty list after inserting notification events, not to save the same data twice.
- Fix #803 
- Reset `notification_events` attribute to an empty list after inserting notification events in `batch/indexer_dvp_delivery.py`
=> Clear notification_events list after inserting events in DVP delivery indexer (25.6)

batch/processor_eth_wst_monitor_txreceipt.py
This pull request updates the `batch/processor_eth_wst_monitor_txreceipt.py` file to enhance error handling during transaction receipt processing. 
- Related to: #812 
Enhancements to transaction receipt processing:
* Added the `DISCARD` parameter from `web3.logs` to the `process_receipt` method across multiple transaction types (`Mint`, `Burn`, `AccountWhiteListAdded`, `AccountWhiteListDeleted`, `TradeRequested`, `TradeCancelled`, `TradeAccepted`, and `TradeRejected`) to improve error handling and avoid processing invalid logs. [[1]](diffhunk://#diff-7711bbe44883be877362b4127aa3ba17ea790fe9c2cca884155238913e8ce7bcL168-R169) [[2]](diffhunk://#diff-7711bbe44883be877362b4127aa3ba17ea790fe9c2cca884155238913e8ce7bcL180-R181) [[3]](diffhunk://#diff-7711bbe44883be877362b4127aa3ba17ea790fe9c2cca8 …
=> Add error handling for event receipt processing in IbetWST transactions

app/model/ibet/token.py, app/model/schema/token.py, app/routers/issuer/bond.py, app/routers/issuer/share.py, docs/ibet_prime.yaml, tests/app/test_bond_tokens_ListAllBondTokens.py, tests/app/test_bond_tokens_RetrieveBondToken.py, tests/app/test_share_tokens_ListAllShareTokens.py, tests/app/test_share_tokens_RetrieveShareToken.py
This pull request introduces enhancements to the `ibet` token model and related components, focusing on handling additional contract attributes (`ibet_wst_*` fields). 
- Related to: #812 
* Updated `IbetStraightBondResponse` and `IbetShareResponse` in `app/model/schema/token.py` to include new fields: `ibet_wst_activated`, `ibet_wst_version`, `ibet_wst_deployed`, and `ibet_wst_address`, with detailed descriptions.
* Added corresponding schema updates to `docs/ibet_prime.yaml` for `IbetShareResponse` and `IbetStraightBondResponse`. [[1]](diffhunk://#diff-e54863847006bb647956a60aebd43bf13e3ce8bf1a59539d4e8692da6bed254eR14047-R14075) [[2]](diffhunk://#diff-e54863847006bb647956a60aebd43bf13e3ce8bf1a59539d4e8692da6bed254eR14688-R14716)
* Enhanced `list_all_bond_tokens` and …
=> Add wst response items

app/model/db/ibet_wst.py, batch/processor_eth_wst_monitor_txreceipt.py, migrations/versions/cfb5c6ce3197_v25_9_0_feature_812_3.py, tests/batch/test_processor_eth_wst_monitor_txreceipt.py
This pull request introduces a new feature to track the gas used in Ethereum transactions (`gas_used`) for the `EthIbetWSTTx` model.
* Updated the `EthIbetWSTTx` model to include the `gas_used` attribute, allowing the application to store and retrieve this information. (`app/model/db/ibet_wst.py`)
* Modified the `run` method in `batch/processor_eth_wst_monitor_txreceipt.py` to populate the `gas_used` field from the transaction receipt data. (`batch/processor_eth_wst_monitor_txreceipt.py`)
=> Add gas_used field to IbetWST transactions

config.py, eth_config.py
This pull request refactors encryption and resource management settings in `config.py` and `eth_config.py` to improve clarity and flexibility. Key changes include streamlining the configuration logic for End-to-End Encryption (E2EE) and adding support for retrieving Ethereum private keys from AWS Secrets Manager.
* Consolidated conditional logic for setting `E2EE_RSA_RESOURCE_MODE` to simplify and unify handling for unit tests, migrations, and local development environments.
* Introduced `ETH_MASTER_PRIVATE_KEY_RESOURCE` to specify the source of the master account's private key (`os_environ` or `aws_secrets_manager`).
* Added support for retrieving the master account's private key from AWS Secrets Manager.
=> Support AWS Secrets Manager for Ethereum master private key management

app/model/schema/ibet_wst.py, docs/ibet_prime.yaml, tests/app/test_ibet_wst_TransferIbetWST.py
This pull request modifies the handling of `valid_after` and `valid_before` fields in the IbetWST transfer functionality.
* [`app/model/schema/ibet_wst.py`](diffhunk://#diff-f68404341792a531155f615f4f170c082a2f86fb1a4c4b7d9908404aa4122b29L146-R149): Changed `valid_after` and `valid_before` fields from `Optional[PositiveInt]` to mandatory `PositiveInt` with default values, ensuring stricter validation.
=> Enforce required integer validation for valid_after and valid_before fields in IbetWST transfer

app/routers/misc/ibet_wst.py, docs/ibet_prime.yaml, tests/app/test_ibet_wst_BurnIbetWSTBalance.py, tests/app/test_ibet_wst_TransferIbetWST.py
This pull request introduces changes to enhance error handling for insufficient balance scenarios in the `IbetWST` module.
* Added a pre-transaction balance check in the `burn_ibet_wst_balance` and `transfer_ibet_wst` endpoints to ensure sufficient token balance before proceeding with transactions. If the balance is insufficient, an `IbetWSTInsufficientBalanceError` is raised. (`app/routers/misc/ibet_wst.py`: [[1]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R247-R252) [[2]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R518-R525)
=> Add pre-transaction balance checks for IbetWST operations

app/routers/issuer/bond.py, app/routers/issuer/share.py, tests/app/test_bond_personal_info_RegisterBondTokenHolderPersonalInfo.py, tests/app/test_share_personal_info_RegisterShareTokenHolderPersonalInfo.py
This pull request introduces functionality to track the history of personal information updates for bond and share token holders.
- Close #869 
- Enhanced the `register_bond_token_holder_personal_info` and `register_share_token_holder_personal_info` endpoints to log personal information changes into the `IDXPersonalInfoHistory` table whenever off-chain personal information is registered. [[1]](diffhunk://#diff-d423ad219858d5cadb48390db542fd1449ff9d6562213d33ff3150f48b7fbbe9R2808-R2821) [[2]](diffhunk://#diff-95d74a3e746fba065d4d5d96590dff5859b62a05b1f1c68769a083b04cad2991R2731-R2744)
=> Add personal info history tracking for off-chain data

app/model/db/ibet_wst.py, batch/processor_eth_wst_monitor_txreceipt.py, tests/batch/test_processor_eth_wst_monitor_txreceipt.py
This pull request improves the handling and clarity of the `ibet_wst_address` field for IbetWST contract transactions, ensures the contract address is set correctly for deploy transactions, and updates the tests to validate this behavior.
**Transaction contract address handling:**
* Updated the transaction processing logic in `batch/processor_eth_wst_monitor_txreceipt.py` to set the `ibet_wst_address` from the transaction receipt when the transaction type is `DEPLOY`.
* Clarified the documentation for the `ibet_wst_address` field in the `EthIbetWSTTx` model to specify that for deploy transactions, the contract address is set upon deployment, while for other transactions, it is set when instructed.
=> Update IbetWST address handling for deploy transactions

app/model/schema/ibet_wst.py, app/routers/misc/ibet_wst.py, docs/ibet_prime.yaml, tests/app/test_ibet_wst_ListIbetWSTTransactions.py
This pull request introduces a new transaction status filter for IbetWST transactions, refactors the status field to use a dedicated enum type.
* Added `IbetWSTTxStatus` enum to `app/model/schema/ibet_wst.py` and refactored all status fields to use this enum instead of raw integers, improving type safety and code clarity. [[1]](diffhunk://#diff-f68404341792a531155f615f4f170c082a2f86fb1a4c4b7d9908404aa4122b29L20-R20) [[2]](diffhunk://#diff-f68404341792a531155f615f4f170c082a2f86fb1a4c4b7d9908404aa4122b29R81-R89) [[3]](diffhunk://#diff-f68404341792a531155f615f4f170c082a2f86fb1a4c4b7d9908404aa4122b29R145-R148) [[4]](diffhunk://#diff-f68404341792a531155f615f4f170c082a2f86fb1a4c4b7d9908404aa4122b29L399-R412)
* Enhanced the transaction listing endpoint in …
=> Add transaction status filtering for IbetWST transactions

app/exceptions.py, app/model/eth/wst.py, app/routers/misc/ibet_wst.py, docs/ibet_prime.yaml, tests/app/test_ibet_wst_RequestIbetWSTTrade.py, tests/app/test_ibet_wst_TransferIbetWST.py
This pull request introduces a new error type to enforce whitelisting checks for IbetWST account transfers and trades. Now, both transfer and trade operations require that the involved accounts are whitelisted; otherwise, a specific error is returned. 
* Added the `IbetWSTAccountNotWhitelistedError` exception, which is raised when either the sender or receiver account is not whitelisted for IbetWST transfer or trade operations (`app/exceptions.py`).
* Updated the transfer and trade endpoints to check the whitelisting status of both accounts before proceeding, raising the new error if either is not listed (`app/routers/misc/ibet_wst.py`). [[1]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607L554-R572) …
=> Add whitelist checks for IbetWST transfer and trade operations

app/model/schema/__init__.py, app/model/schema/ibet_wst.py, app/routers/issuer/token_common.py, app/routers/misc/ibet_wst.py, docs/ibet_prime.yaml, tests/app/test_ibet_wst_GetIbetWSTWhiteList.py, tests/app/test_ibet_wst_RetrieveIbetWSTWhitelistAccounts.py, tests/app/test_token_common_GetIbetWSTWhitelistWithPersonalInfo.py, tests/app/test_token_common_RetrieveIbetWSTWhitelistAccountsWithPersonalInfo.py
This pull request introduces new API endpoints to support retrieving IbetWST whitelist accounts along with associated personal information.
- Close #874
**API & Schema Enhancements**
* Added two new response models: `RetrieveIbetWSTWhitelistAccountsWithPersonalInfoResponse` and `GetIbetWSTWhitelistWithPersonalInfoResponse`, along with supporting schema classes (`IbetWSTWhitelistAccountWithPersonalInfo`) to represent whitelist accounts with personal information.
**Backend Implementation**
* Implemented two new API endpoints in `app/routers/issuer/token_common.py`:
- `retrieve_ibet_wst_whitelist_accounts_with_personal_info`: returns all whitelist accounts for a token with personal info.
- `get_ibet_wst_whitelist_with_personal_info`: returns whitelist status and personal info for a specific …
=> Add endpoints to retrieve IbetWST whitelist accounts with personal information

app/model/db/ibet_wst.py, app/model/eth/wst.py, app/model/schema/ibet_wst.py, app/routers/misc/ibet_wst.py, batch/processor_eth_wst_monitor_txreceipt.py, docs/ibet_prime.yaml, tests/app/model/eth/test_ERC20.py, tests/app/test_ibet_wst_GetIbetWSTTransaction.py, tests/app/test_ibet_wst_ListIbetWSTTransactions.py, tests/batch/test_processor_eth_wst_monitor_txreceipt.py
This pull request enhances support for StableCoin (SC) token decimals in IbetWST trade-related transactions. It ensures that SC values are accurately represented and displayed according to their decimals, improving both backend data integrity and API responses.
- Related to #812 
**StableCoin decimals support and display:**
- Added a `sc_decimals` field to all IbetWST trade event log TypedDicts (`IbetWSTEventLogTradeRequested`, `IbetWSTEventLogTradeCancelled`, `IbetWSTEventLogTradeAccepted`, `IbetWSTEventLogTradeRejected`) to store the decimals of the StableCoin token. [[1]](diffhunk://#diff-4fb31064e27d1d13f8685fa2c590e7e948d17b388c95fb1f8e616615497e52fbR194) [[2]](diffhunk://#diff-4fb31064e27d1d13f8685fa2c590e7e948d17b388c95fb1f8e616615497e52fbR208) …
=> Add support for StableCoin decimals in IbetWST transactions

package-lock.json, package.json
This pull request makes a minor update to the version specification for the `hardhat` development dependency in `package.json`, changing it from a caret (`^`) to a tilde (`~`) to restrict updates to patch versions only.
Related to https://github.com/BoostryJP/ibet-Prime/pull/893
- Bump hardhat: 2.26.2 -> 2.26.3
=> Update hardhat to version 2.26.3 and adjust versioning in package files

app/model/db/ibet_wst.py, app/routers/misc/ibet_wst.py
This pull request introduces a small fix and a minor logic update related to handling event logs in ibet WST transactions. The main changes ensure that event log processing only occurs when an event log is present, preventing potential errors.
- Fix #892 
Event log handling improvements:
* Added checks to ensure that event log processing in both `list_ibet_wst_transactions` and `get_ibet_wst_transaction` only occurs if the `event_log` is not `None`, improving robustness. [[1]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R363) [[2]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607R444)
Minor typo fix:
* Corrected a comment typo in the `EthIbetWSTTx` class, changing `tx_tye` to `tx_type` for clarity.
=> Fix event log handling for trade-related transactions by adding null check for event_log

pyproject.toml, uv.lock
This pull request updates dependencies in the `pyproject.toml` file to newer versions, focusing on improving compatibility and security for the project.
- none
Dependency version updates:
* Upgraded the `fastapi` dependency from version `0.115.0` to `0.116.1` in the main dependencies list to incorporate the latest fixes and features.
* Upgraded the `aiohttp` dependency from version `3.9.3` to `3.12.15` in the `ibet-explorer` group to ensure improved stability and security.
=> Bump FastAPI to 0.116.1 and aiohttp to 3.12.15 in pyproject.toml

app/routers/misc/ibet_wst.py, tests/app/test_ibet_wst_GetIbetWSTBalance.py, uv.lock
This pull request standardizes the handling of Ethereum addresses in the `ibet_wst` router and its associated tests by ensuring that all addresses are converted to checksum format using `to_checksum_address`. 
- Related to #812 
**Address normalization improvements:**
* Updated all database queries in `app/routers/misc/ibet_wst.py` to use `to_checksum_address(ibet_wst_address)` when filtering by `ibet_wst_address`, ensuring consistent address formatting throughout the codebase. [[1]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607L212-R214) [[2]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607L248-R252) [[3]](diffhunk://#diff-5f30c7009cfc64532aa4bab8d802cd4bd1f229a48d83bf105b2e22d68d609607L598-R604) …
=> Refactor ibet_wst address handling to use checksum addresses for consistency

app/model/schema/account.py, docs/ibet_prime.yaml, tests/app/test_accounts_GenerateIssuerAuthToken.py
This pull request updates the validation logic for the `valid_duration` field in the account authentication token request, removing the upper limit restriction.
- Close #908 
**Validation and schema changes:**
* The maximum value restriction (`le=259200`) for the `valid_duration` field in the `AccountAuthTokenRequest` model (`account.py`) has been removed, allowing any non-negative integer value. The field description is also updated.
* The OpenAPI specification (`ibet_prime.yaml`) is updated: the maximum value for `valid_duration` is removed, and the description and schema title are updated to match the code.
=> Refactor AccountAuthTokenRequest schema
